var _=_||{};(function(_){var window=this;
try{
var ua;var ta;_.q=function(a){return function(){return _.ba[a].apply(this,arguments)}};var _DumpException=function(a){throw a;};_.ba=[];_.ca=_.ca||{};_.r=this;_.fa=function(a){return void 0!==a};
_.ia=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.ma=function(a){return"array"==(0,_.ia)(a)};_.pa=function(a){return"string"==typeof a};_.ra="closure_uid_"+(1E9*Math.random()>>>0);ta=function(a,b,c){return a.call.apply(a.bind,arguments)};
ua=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};_.s=function(a,b,c){_.s=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ta:ua;return _.s.apply(null,arguments)};
_.va=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.za=Date.now||function(){return+new Date};_.u=function(a,b){function c(){}c.prototype=b.prototype;a.J=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.kt=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};
_.Da=window.gadgets||{};_.Ea=window.osapi=window.osapi||{};_.google=window.google||{};
}catch(e){_._DumpException(e)}
try{
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},client:{jsonpOverride:!1},csi:{rate:0.01},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/:session_prefix:_/widget/render/badge?usegapi=1"},":socialhost:":"https://apis.google.com",":im_socialhost:":"https://plus.googleapis.com",card:{params:{s:"#",userid:"&"},url:":socialhost:/:session_prefix:_/hovercard/internalcard"},
":signuphost:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton?usegapi=1"},plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true&usegapi=1"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle?usegapi=1"},plus_followers:{url:":socialhost:/_/im/_/widget/render/plus/followers?usegapi=1"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator?usegapi=1"},appcirclepicker:{url:":socialhost:/:session_prefix:_/widget/render/appcirclepicker"},
page:{url:':socialhost:/:session_prefix:_/widget/render/page?usegapi=1"'},person:{url:':socialhost:/:session_prefix:_/widget/render/person?usegapi=1"'},community:{url:':socialhost:/:session_prefix:_/widget/render/community?usegapi=1"'},follow:{url:":socialhost:/:session_prefix:_/widget/render/follow?usegapi=1"},commentcount:{url:":socialhost:/:session_prefix:_/widget/render/commentcount?usegapi=1"},comments:{url:":socialhost:/:session_prefix:_/widget/render/comments?usegapi=1"},youtube:{url:":socialhost:/:session_prefix:_/widget/render/youtube?usegapi=1"},
reportabuse:{url:":socialhost:/:session_prefix:_/widget/render/reportabuse?usegapi=1"},":source:":"1p"},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"pos.plusones.list":!0,"pos.plusones.get":!0,"pos.plusones.insert":!0,"pos.plusones.delete":!0,"pos.plusones.getSignupState":!0},requestCache:{enabled:!0},versions:{pos:"v1"},rpc:"/rpc",root:"https://content.googleapis.com","root-1p":"https://clients6.google.com",sessionCache:{enabled:!0},transport:{isProxyShared:!0}, xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:!1}},report:{apis:["iframes\\..*","gadgets\\..*","gapi\\.appcirclepicker\\..*","gapi\\.client\\..*"],rate:1E-4}});

}catch(e){_._DumpException(e)}
try{
_.Fa=function(a,b){return b};_.D=function(a,b){var c=a.split("."),d=_.r;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&(0,_.fa)(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};_.E=function(a,b){b=(0,_.Fa)(a,b);(0,_.D)(a,b)};
_.Ga=window;_.Ha=window.document;_.Ia=_.Ga.location;_.Ja=/\[native code\]/;_.La=function(a,b,c){return a[b]=a[b]||c};_.Ma=function(){var a;if((a=Object.create)&&_.Ja.test(a))a=a(null);else{a={};for(var b in a)a[b]=void 0}return a};_.Na=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};_.Oa=function(a,b){if(!a)throw Error(b||"");};_.Ra=(0,_.La)(_.Ga,"gapi",{});
_.Sa=function(a,b,c){var d=new RegExp("([#].*&|[#])"+b+"=([^&#]*)","g");b=new RegExp("([?#].*&|[?#])"+b+"=([^&#]*)","g");if(a=a&&(d.exec(a)||b.exec(a)))try{c=(0,window.decodeURIComponent)(a[2])}catch(e){}return c};_.Wa=function(a,b,c){(0,_.Va)(a,b,c,"add","at")};_.Va=function(a,b,c,d,e){if(a[d+"EventListener"])a[d+"EventListener"](b,c,!1);else if(a[e+"tachEvent"])a[e+"tachEvent"]("on"+b,c)};_.Ya=(0,_.La)(_.Ga,"___jsl",(0,_.Ma)());(0,_.La)(_.Ya,"I",0);(0,_.La)(_.Ya,"hel",10);var db;var cb;var ab;var $a;var Za;Za=function(a){var b=window.___jsl=window.___jsl||{};b[a]=b[a]||[];return b[a]};$a=function(a){var b=window.___jsl=window.___jsl||{};b.cfg=!a&&b.cfg||{};return b.cfg};ab=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};
_.bb=function(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&(a[c]&&b[c]&&"object"===typeof a[c]&&"object"===typeof b[c]&&!ab(a[c])&&!ab(b[c])?(0,_.bb)(a[c],b[c]):b[c]&&"object"===typeof b[c]?(a[c]=ab(b[c])?[]:{},(0,_.bb)(a[c],b[c])):a[c]=b[c])};
cb=function(a){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);var b;try{b=window.JSON.parse(a)}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ("+a+"\n)"))()}catch(d){}if("object"===typeof b)return b;try{b=(new Function("return ({"+a+"\n})"))()}catch(e){}return"object"===typeof b?b:{}}};
db=function(a){$a(!0);var b=window.___gcfg,c=Za("cu");if(b&&b!==window.___gu){var d={};(0,_.bb)(d,b);c.push(d);window.___gu=b}var b=Za("cu"),e=window.document.scripts||window.document.getElementsByTagName("script")||[],d=[],f=[];f.push.apply(f,Za("us"));for(var g=0;g<e.length;++g)for(var k=e[g],l=0;l<f.length;++l)k.src&&0==k.src.indexOf(f[l])&&d.push(k);0==d.length&&0<e.length&&e[e.length-1].src&&d.push(e[e.length-1]);for(e=0;e<d.length;++e)d[e].getAttribute("gapi_processed")||(d[e].setAttribute("gapi_processed",
!0),(f=d[e])?(g=f.nodeType,f=3==g||4==g?f.nodeValue:f.textContent||f.innerText||f.innerHTML||""):f=void 0,(f=cb(f))&&b.push(f));a&&(d={},(0,_.bb)(d,a),c.push(d));d=Za("cd");a=0;for(b=d.length;a<b;++a)(0,_.bb)($a(),d[a]);d=Za("ci");a=0;for(b=d.length;a<b;++a)(0,_.bb)($a(),d[a]);a=0;for(b=c.length;a<b;++a)(0,_.bb)($a(),c[a])};_.G=function(a,b){if(!a)return $a();for(var c=a.split("/"),d=$a(),e=0,f=c.length;d&&"object"===typeof d&&e<f;++e)d=d[c[e]];return e===c.length&&void 0!==d?d:b}; _.fb=function(a,b){var c=a;if("string"===typeof a){for(var d=c={},e=a.split("/"),f=0,g=e.length;f<g-1;++f)var k={},d=d[e[f]]=k;d[e[f]]=b}db(c)};
var gb=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),(0,_.La)(_.Ya,"ci",[]).push(a),window.__GOOGLEAPIS=void 0)};gb&&gb();db();(0,_.E)("gapi.config.get",_.G);(0,_.E)("gapi.config.update",_.fb);
}catch(e){_._DumpException(e)}
try{
var Hb;var Fb;var Eb;var Ab;var zb;var yb;var xb;var wb;var ub;var tb;var sb;var rb;var qb;var nb;var mb;_.jb=function(a){return!!a&&"object"===typeof a&&_.Ja.test(a.push)};_.kb=function(a,b,c){if(a){(0,_.Oa)((0,_.jb)(a),"arrayForEach was called with a non array value");for(var d=0;d<a.length;d++)b.call(c,a[d],d)}};
_.lb=function(a,b,c){if(a)if((0,_.jb)(a))(0,_.kb)(a,b,c);else{(0,_.Oa)("object"===typeof a,"objectForEach was called with a non object value");c=c||a;for(var d in a)(0,_.Na)(a,d)&&void 0!==a[d]&&b.call(c,a[d],d)}};mb=function(a){a=a.sort();for(var b=[],c=void 0,d=0;d<a.length;d++){var e=a[d];e!=c&&b.push(e);c=e}return b};nb=function(){var a=[],b=_.Ya.H;b&&(0,_.lb)(b,function(b){a.push.apply(a,b.L)});return mb(a)};
_.pb=function(a){if(_.Ja.test(Object.keys))return Object.keys(a);var b=[],c;for(c in a)(0,_.Na)(a,c)&&b.push(c);return b};xb={};yb=0;zb=(0,_.Ma)();Ab=(0,_.Ma)();_.Db=function(a){if(void 0===qb){var b=(0,_.G)("report")||{},c=b.rate,d=Math.random();if(qb="number"===typeof c&&c>d)Ab["rate."+c+"-"+d]=!0,tb=b.timeout||1E3,rb=b.host||"https://plus.google.com",sb=b.path||"/_/widget/report",wb=b.apis||[]}if(!qb)return!1;if(wb)for(b=0;b<wb.length;b++)if((new RegExp("^"+wb[b]+"$")).test(a))return!0;return!1};
Eb=function(a){delete xb[a]};Fb=function(){ub&&(_.Ga.clearTimeout(ub),ub=0);ub=_.Ga.setTimeout(function(){var a;a=window.document.location;a=a.protocol+"//"+a.host+a.pathname;var b=(0,_.pb)(Ab).join(":");a=[rb,sb,"?api=",(0,window.encodeURIComponent)(b),"&url=",(0,window.encodeURIComponent)(a),"&loaded=",(0,window.encodeURIComponent)(nb().join(":"))].join("");Ab=(0,_.Ma)();var b=new window.Image,c=yb++;xb[c]=b;b.onload=b.onerror=(0,_.va)(Eb,c);b.src=a;ub=0},tb)}; _.Gb=function(a){zb[a]||(Ab[a]=!0,zb[a]=!0,Fb())};Hb=_.Fa;_.Fa=function(a,b){var c=Hb(a,b);"function"===typeof b&&(0,_.Db)(a)&&(c=function(c){(0,_.Gb)(a);return b.apply(this,arguments)});return c};

}catch(e){_._DumpException(e)}
try{
_.Lb=window.gapi&&window.gapi.util||{};
}catch(e){_._DumpException(e)}
try{
var Nc=_.Lb=_.Lb||{};window.___jsl=window.___jsl||{};Nc.Xn={A:function(){return window.___jsl.bsh},su:function(){return window.___jsl.h},Wq:function(a){window.___jsl.bsh=a},xH:function(a){window.___jsl.h=a}};
}catch(e){_._DumpException(e)}
try{
var Pc;var Oc;Oc=/^https?:\/\/(?:\w|[\-\.])+\.google\.(?:\w|[\-:\.])+(?:\/[^\?\#]*)?\/u\/(\d)\//;Pc=/^https?:\/\/(?:\w|[\-\.])+\.google\.(?:\w|[\-:\.])+(?:\/[^\?\#]*)?\/b\/(\d{10,})\//;_.Qc=function(a){var b=(0,_.G)("googleapis.config/sessionIndex");null==b&&(b=window.__X_GOOG_AUTHUSER);if(null==b){var c=window.google;c&&(b=c.authuser)}null==b&&(a=a||window.location.href,b=(0,_.Sa)(a,"authuser")||null,null==b&&(b=(b=a.match(Oc))?b[1]:null));return null==b?null:String(b)};
_.Rc=function(a){var b=(0,_.G)("googleapis.config/sessionDelegate");null==b&&(b=(a=(a||window.location.href).match(Pc))?a[1]:null);return null==b?null:String(b)};_.Sc=function(a,b){var c=(0,_.Qc)(a)||b,d=(0,_.Rc)(a),e="";c&&(e+="u/"+c+"/");d&&(e+="b/"+d+"/");return e||null};

}catch(e){_._DumpException(e)}
try{
_.Tc=function(a){var b;if(b=(0,_.G)("enableMultilogin"))if(b=a("cookie_policy"))b=String(a("immediate")||""),a=String(a("prompt")||""),b=!("true"===b.toLowerCase()||"none"===a.toLowerCase());return b?!0:!1};
_.Uc=function(a,b,c){a=String(a);if(null!=((0,_.Sa)(a,"authuser")||null)||null!=((0,_.Sa)(a,"hd")||null))return a;b=(0,_.Qc)(b);if(c){var d=a,e=d.match(/^((https?:)?\/\/[^\/?#]*)?(\/[^\/?#]+)\/[0-9]+([\/][^?#]*)([?#].*)?$/);if(e&&e[0]){var f=e[1],g=e[4],k=e[5];e[3]=="/"+c&&(d=(f||"")+(g||"/")+(k||""))}if((e=d.match(/^(((https?:)?\/\/[^\/?#]*)([\/][^?#]*)?|([\/][^?#]*))([?#].*)?$/))&&e[0]){var f=e[2],l=e[4]||e[5],k=e[6];null!=b&&(d=(f||"")+"/"+c+"/"+(0,window.encodeURIComponent)(b)+(l||"/")+(k||""));
return d}}null==b?(0,_.Tc)(function(b){return(0,_.Sa)(a,b)||null})||(l=(0,window.encodeURIComponent)("authuser")+"=0"):l=b.match(/^([-a-z0-9]+[.])+[-a-z0-9]+$/)?[(0,window.encodeURIComponent)("authuser")+"=",(0,window.encodeURIComponent)(String(b)),"&"+(0,window.encodeURIComponent)("hd")+"=",(0,window.encodeURIComponent)(b)].join(""):["authuser=",(0,window.encodeURIComponent)(b)].join("");c=a.split("#");b=c[0].indexOf("?");0>b?c[0]=[c[0],"?",l].join(""):(d=[c[0]],b<c[0].length-1&&d.push("&"),d.push(l), c[0]=d.join(""));return d=c.join("#")};_.google.oQ=_.Uc;_.google.jp=_.Qc;_.google.JP=_.Rc;_.google.KP=_.Sc;

}catch(e){_._DumpException(e)}
try{
var Vc=function(){this.B=-1};_.Wc=function(){this.B=-1;this.B=64;this.A=[];this.G=[];this.K=[];this.D=[];this.D[0]=128;for(var a=1;a<this.B;++a)this.D[a]=0;this.F=this.C=0;this.reset()};(0,_.u)(_.Wc,Vc);_.Wc.prototype.reset=function(){this.A[0]=1732584193;this.A[1]=4023233417;this.A[2]=2562383102;this.A[3]=271733878;this.A[4]=3285377520;this.F=this.C=0};
var Xc=function(a,b,c){c||(c=0);var d=a.K;if((0,_.pa)(b))for(var e=0;16>e;e++)d[e]=b.charCodeAt(c)<<24|b.charCodeAt(c+1)<<16|b.charCodeAt(c+2)<<8|b.charCodeAt(c+3),c+=4;else for(e=0;16>e;e++)d[e]=b[c]<<24|b[c+1]<<16|b[c+2]<<8|b[c+3],c+=4;for(e=16;80>e;e++){var f=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(f<<1|f>>>31)&4294967295}b=a.A[0];c=a.A[1];for(var g=a.A[2],k=a.A[3],l=a.A[4],m,e=0;80>e;e++)40>e?20>e?(f=k^c&(g^k),m=1518500249):(f=c^g^k,m=1859775393):60>e?(f=c&g|k&(c|g),m=2400959708):(f=c^g^k,m=3395469782),
f=(b<<5|b>>>27)+f+l+m+d[e]&4294967295,l=k,k=g,g=(c<<30|c>>>2)&4294967295,c=b,b=f;a.A[0]=a.A[0]+b&4294967295;a.A[1]=a.A[1]+c&4294967295;a.A[2]=a.A[2]+g&4294967295;a.A[3]=a.A[3]+k&4294967295;a.A[4]=a.A[4]+l&4294967295};
_.Wc.prototype.update=function(a,b){(0,_.fa)(b)||(b=a.length);for(var c=b-this.B,d=0,e=this.G,f=this.C;d<b;){if(0==f)for(;d<=c;)Xc(this,a,d),d+=this.B;if((0,_.pa)(a))for(;d<b;){if(e[f]=a.charCodeAt(d),++f,++d,f==this.B){Xc(this,e);f=0;break}}else for(;d<b;)if(e[f]=a[d],++f,++d,f==this.B){Xc(this,e);f=0;break}}this.C=f;this.F+=b};
_.Wc.prototype.M=function(){var a=[],b=8*this.F;56>this.C?this.update(this.D,56-this.C):this.update(this.D,this.B-(this.C-56));for(var c=this.B-1;56<=c;c--)this.G[c]=b&255,b/=256;Xc(this,this.G);for(c=b=0;5>c;c++)for(var d=24;0<=d;d-=8)a[b]=this.A[c]>>d&255,++b;return a};
_.Yc=function(){this.A=new _.Wc};_.h=_.Yc.prototype;_.h.reset=function(){this.A.reset()};_.h.Uy=function(a){this.A.update(a)};_.h.Lt=function(){return this.A.M()};_.h.Br=function(a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var b=[],c=0,d=a.length;c<d;++c)b.push(a.charCodeAt(c));this.Uy(b)};_.h.sf=function(){for(var a=this.Lt(),b="",c=0;c<a.length;c++)b+="0123456789ABCDEF".charAt(Math.floor(a[c]/16))+"0123456789ABCDEF".charAt(a[c]%16);return b};

}catch(e){_._DumpException(e)}
try{
var kh;var oh;var th;var nh;var ph;var mh;var sh;var rh;var kh;var lh;_.qh=function(){var a;kh?(a=new _.Ga.Uint32Array(1),lh.getRandomValues(a),a=Number("0."+a[0])):(a=mh,a+=(0,window.parseInt)(nh.substr(0,20),16),nh=oh(nh),a=a/(ph+Math.pow(16,20)));return a};lh=_.Ga.crypto;kh=!1;rh=0;sh=0;mh=1;ph=0;nh="";th=function(a){a=a||_.Ga.event;var b=a.screenX+a.clientX<<16,b=b+(a.screenY+a.clientY),b=(new Date).getTime()%1E6*b;mh=mh*b%ph;0<rh&&++sh==rh&&(0,_.Va)(_.Ga,"mousemove",th,"remove","de")};
oh=function(a){var b=new _.Yc;b.Br(a);return b.sf()};kh=!!lh&&"function"==typeof lh.getRandomValues;kh||(ph=1E6*(window.screen.width*window.screen.width+window.screen.height),nh=oh(_.Ha.cookie+"|"+_.Ha.location+"|"+(new Date).getTime()+"|"+Math.random()),rh=(0,_.G)("random/maxObserveMousemove")||0,0!=rh&&(0,_.Wa)(_.Ga,"mousemove",th));

}catch(e){_._DumpException(e)}
try{
var Nh;var Mh;var Lh;var Kh;var Jh;var Ih;var Fh;var Eh;var Dh;var Ch;var Bh;var Ah;var zh;var yh;var xh;var vh;_.uh=function(a,b){a=a||{};for(var c in a)(0,_.Na)(a,c)&&(b[c]=a[c])};vh=/^([^?#]*)(\?([^#]*))?(\#(.*))?$/;_.wh=/^https?:\/\/[^\/%\\?#\s]+\/[^\s]*$/i;xh=function(a,b){var c=[];if(a)for(var d in a)if((0,_.Na)(a,d)&&null!=a[d]){var e=b?b(a[d]):a[d];c.push((0,window.encodeURIComponent)(d)+"="+(0,window.encodeURIComponent)(e))}return c};
yh=function(a){return a.kt+(0<a.query.length?"?"+a.query.join("&"):"")+(0<a.vl.length?"#"+a.vl.join("&"):"")};zh=function(a){a=a.match(vh);var b=(0,_.Ma)();b.kt=a[1];b.query=a[3]?[a[3]]:[];b.vl=a[5]?[a[5]]:[];return b};Ah=/'/g;Bh=/"/g;Ch=/>/g;Dh=/</g;Eh=/&/g;Fh=function(a){for(;a.firstChild;)a.removeChild(a.firstChild)};
_.Gh=function(a,b){var c="";2E3<b.length&&(c=b.substring(2E3),b=b.substring(0,2E3));var d=a.createElement("div"),e=a.createElement("a");e.href=b;d.appendChild(e);d.innerHTML=d.innerHTML;b=String(d.firstChild.href);d.parentNode&&d.parentNode.removeChild(d);return b+c};_.Hh=function(a,b,c,d){a=zh(a);a.query.push.apply(a.query,xh(b,d));a.vl.push.apply(a.vl,xh(c,d));return yh(a)};
Ih=function(a){return String(a).replace(Eh,"&amp;").replace(Dh,"&lt;").replace(Ch,"&gt;").replace(Bh,"&quot;").replace(Ah,"&#39;")};Kh=function(){var a=_.Ya.onl;if(!a){a=(0,_.Ma)();_.Ya.onl=a;var b=(0,_.Ma)();a.e=function(a){var d=b[a];d&&(delete b[a],d())};a.a=function(a,d){b[a]=d};a.r=function(a){delete b[a]}}return a};Lh=function(a,b){var c=b.onload;return"function"===typeof c?(Kh().a(a,c),c):null}; Mh=function(a){(0,_.Oa)(/^\w+$/.test(a),"Unsupported id - "+a);Kh();return'onload="window.___jsl.onl.e(&#34;'+a+'&#34;)"'};Nh=function(a){Kh().r(a)};
var Uh;var Qh;var Ph;_.Oh={allowtransparency:"true",frameborder:"0",hspace:"0",marginheight:"0",marginwidth:"0",scrolling:"no",style:"",tabindex:"0",vspace:"0",width:"100%"};Ph={allowtransparency:!0,onload:!0};Qh=0;_.Rh=function(a,b){var c,d=0;do c=b.id||["I",Qh++,"_",(new Date).getTime()].join("");while(a.getElementById(c)&&5>++d);(0,_.Oa)(5>d,"Error creating iframe id");return c};_.Sh=function(a,b){return a?b+"/"+a:""};
_.Th=function(a,b,c,d){var e={},f={};a.documentMode&&9>a.documentMode&&(e.hostiemode=a.documentMode);(0,_.uh)(d.queryParams||{},e);(0,_.uh)(d.fragmentParams||{},f);var g=d.connectWithQueryParams?e:f,k=d.pfname,l=(0,_.Ma)();l.id=c;l.parent=a.location.protocol+"//"+a.location.host;c=(0,_.Sa)(a.location.href,"parent");k=k||"";!k&&c&&(k=(0,_.Sh)((0,_.Sa)(a.location.href,"id",""),(0,_.Sa)(a.location.href,"pfname","")));l.pfname=k;(0,_.uh)(l,g);(l=(0,_.Sa)(b,"rpctoken")||e.rpctoken||f.rpctoken)||(l=g.rpctoken=
d.rpctoken||String(Math.round(1E8*(0,_.qh)())));d.rpctoken=l;g=a.location.href;a=(0,_.Ma)();(l=(0,_.Sa)(g,"_bsh",_.Ya.bsh))&&(a._bsh=l);(g=_.Ya.dpo?_.Ya.h:(0,_.Sa)(g,"jsh",_.Ya.h))&&(a.jsh=g);d.hintInFragment?(0,_.uh)(a,f):(0,_.uh)(a,e);return(0,_.Hh)(b,e,f,d.paramsSerializer)};Uh=function(a){(0,_.Oa)(!a||_.wh.test(a),"Illegal url for new iframe - "+a)};
_.Vh=function(a,b,c,d,e){Uh(c.src);var f,g=Lh(d,c),k=g?Mh(d):"";try{f=a.createElement('<iframe frameborder="'+Ih(String(c.frameborder))+'" scrolling="'+Ih(String(c.scrolling))+'" '+k+' name="'+Ih(String(c.name))+'"/>')}catch(l){f=a.createElement("iframe"),g&&(f.onload=function(){f.onload=null;g.call(this)},Nh(d))}for(var m in c)a=c[m],"style"===m&&"object"===typeof a?(0,_.uh)(a,f.style):Ph[m]||f.setAttribute(m,String(a));(m=e&&e.beforeNode||null)||e&&e.dontclear||Fh(b);b.insertBefore(f,m);f=m?m.previousSibling: b.lastChild;c.allowtransparency&&(f.allowTransparency=!0);return f};
var Zh;var Wh;Wh=/^:[\w]+$/;_.Xh=/:([a-zA-Z_]+):/g;_.Yh=function(){var a=(0,_.Qc)()||"0",b=(0,_.Rc)(),c=(0,_.Sc)(void 0,a),d=!1===(0,_.G)("isLoggedIn"),e=d?"_/im/":"";e&&(c="");var f=(0,_.G)("iframes/:socialhost:"),g=(0,_.G)("iframes/:im_socialhost:");return Jh={socialhost:f,ctx_socialhost:d?g:f,session_index:a,session_delegate:b,session_prefix:c,im_prefix:e}};Zh=function(a,b){return(0,_.Yh)()[b]||""};_.$h=function(a){return(0,_.Gh)(_.Ha,a.replace(_.Xh,Zh))};
_.ai=function(a){var b=a;Wh.test(a)&&(b=(0,_.G)("iframes/"+b.substring(1)+"/url"),(0,_.Oa)(!!b,"Unknown iframe url config for - "+a));return(0,_.$h)(b)};
_.bi=function(a,b,c){var d=c||{};c=d.attributes||{};(0,_.Oa)(!d.allowPost||!c.onload,"onload is not supported by post iframe");a=(0,_.ai)(a);c=b.ownerDocument||_.Ha;var e=(0,_.Rh)(c,d);a=(0,_.Th)(c,a,e,d);var f=(0,_.Ma)();(0,_.uh)(_.Oh,f);(0,_.uh)(d.attributes,f);f.name=f.id=e;f.src=a;d.eurl=a;if((d||{}).allowPost&&2E3<a.length){var g=zh(a);f.src="";f["data-postorigin"]=a;a=(0,_.Vh)(c,b,f,e);var k;if(-1!=window.navigator.userAgent.indexOf("WebKit")){k=a.contentWindow.document;k.open();var f=k.createElement("div"),
l={},m=e+"_inner";l.name=m;l.src="";l.style="display:none";(0,_.Vh)(c,f,l,m,d)}f=(d=g.query[0])?d.split("&"):[];d=[];for(l=0;l<f.length;l++)m=f[l].split("=",2),d.push([(0,window.decodeURIComponent)(m[0]),(0,window.decodeURIComponent)(m[1])]);g.query=[];f=yh(g);g=c.createElement("form");g.action=f;g.method="POST";g.target=e;g.style.display="none";for(e=0;e<d.length;e++)f=c.createElement("input"),f.type="hidden",f.name=d[e][0],f.value=d[e][1],g.appendChild(f);b.appendChild(g);g.submit();g.parentNode.removeChild(g); k&&k.close();b=a}else b=(0,_.Vh)(c,b,f,e,d);return b};

}catch(e){_._DumpException(e)}
try{
_.Lb.va=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);/^[\w\-]*:\/\//.test(a)||(a=window.location.href);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");-1!=c&&(b=b.substring(0,c));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==a)throw Error("b");var c="",d=b.indexOf(":");if(-1!=d){var e=b.substring(d+1),b=b.substring(0,d);if("http"===a&&"80"!==e||"https"===a&&"443"!== e)c=":"+e}return a+"://"+b+c};

}catch(e){_._DumpException(e)}
try{
_.M=_.M||{};
}catch(e){_._DumpException(e)}
try{
_.M=_.M||{};_.M.xm=function(a,b,c){for(var d=[],e=2,f=arguments.length;e<f;++e)d.push(arguments[e]);return function(){for(var c=d.slice(),e=0,f=arguments.length;e<f;++e)c.push(arguments[e]);return b.apply(a,c)}};_.M.Sj=function(a){var b,c,d={};for(b=0;c=a[b];++b)d[c]=c;return d};

}catch(e){_._DumpException(e)}
try{
_.M=_.M||{};
(function(){function a(a,b){return String.fromCharCode(b)}var b={0:!1,10:!0,13:!0,34:!0,39:!0,60:!0,62:!0,92:!0,8232:!0,8233:!0,65282:!0,65287:!0,65308:!0,65310:!0,65340:!0};_.M.escape=function(a,b){if(a){if("string"===typeof a)return _.M.pl(a);if("Array"===typeof a)for(var e=0,f=a.length;e<f;++e)a[e]=_.M.escape(a[e]);else if("object"===typeof a&&b){e={};for(f in a)a.hasOwnProperty(f)&&(e[_.M.pl(f)]=_.M.escape(a[f],!0));return e}}return a};_.M.pl=function(a){if(!a)return a;for(var d=[],e,f,g=0,k= a.length;g<k;++g)e=a.charCodeAt(g),f=b[e],!0===f?d.push("&#",e,";"):!1!==f&&d.push(a.charAt(g));return d.join("")};_.M.TQ=function(b){return b?b.replace(/&#([0-9]+);/g,a):b}})();

}catch(e){_._DumpException(e)}
try{
_.jh=_.jh||{};_.jh.HD=function(){var a=0,b=0;window.self.innerHeight?(a=window.self.innerWidth,b=window.self.innerHeight):window.document.documentElement&&window.document.documentElement.clientHeight?(a=window.document.documentElement.clientWidth,b=window.document.documentElement.clientHeight):window.document.body&&(a=window.document.body.clientWidth,b=window.document.body.clientHeight);return{width:a,height:b}};

}catch(e){_._DumpException(e)}
try{
_.jh=_.jh||{};
(function(){function a(a,c){window.getComputedStyle(a,"").getPropertyValue(c).match(/^([0-9]+)/);return(0,window.parseInt)(RegExp.$1,10)}_.jh.Eb=function(){var b=_.jh.HD().height,c=window.document.body,d=window.document.documentElement;if("CSS1Compat"===window.document.compatMode&&d.scrollHeight)return d.scrollHeight!==b?d.scrollHeight:d.offsetHeight;if(0<=window.navigator.userAgent.indexOf("AppleWebKit")){b=0;for(c=[window.document.body];0<c.length;){var e=c.shift(),d=e.childNodes;if("undefined"!==
typeof e.style){var f=e.style.overflowY;f||(f=(f=window.document.defaultView.getComputedStyle(e,null))?f.overflowY:null);if("visible"!=f&&"inherit"!=f&&(f=e.style.height,f||(f=(f=window.document.defaultView.getComputedStyle(e,null))?f.height:""),0<f.length&&"auto"!=f))continue}for(e=0;e<d.length;e++){f=d[e];if("undefined"!==typeof f.offsetTop&&"undefined"!==typeof f.offsetHeight)var g=f.offsetTop+f.offsetHeight+a(f,"margin-bottom"),b=Math.max(b,g);c.push(f)}}return b+a(window.document.body,"border-bottom")+ a(window.document.body,"margin-bottom")+a(window.document.body,"padding-bottom")}if(c&&d)return e=d.scrollHeight,f=d.offsetHeight,d.clientHeight!==f&&(e=c.scrollHeight,f=c.offsetHeight),e>b?e>f?e:f:e<f?e:f}})();

}catch(e){_._DumpException(e)}
try{
_.sc=function(){function a(a,b){if(!(a<c)&&d)if(2===a&&d.warn)d.warn(b);else if(3===a&&d.error)try{d.error(b)}catch(g){}else d.log&&d.log(b)}var b=function(b){a(1,b)};_.Kb=function(b){a(2,b)};_.Ib=function(b){a(3,b)};_.rc=function(){};b.INFO=1;b.WARNING=2;b.NONE=4;var c=1,d=window.console?window.console:window.opera?window.opera.postError:void 0;return b}();

}catch(e){_._DumpException(e)}
try{
_.M=_.M||{};(function(){var a=[];_.M.sQ=function(b){a.push(b)};_.M.EQ=function(){for(var b=0,c=a.length;b<c;++b)a[b]()}})();
}catch(e){_._DumpException(e)}
try{
_.tc=function(a){for(var b=0;b<this.length;b++)if(this[b]===a)return b;return-1};_.uc=function(a,b){var c=(0,_.La)(_.Ya,"watt",(0,_.Ma)());(0,_.La)(c,a,b)};_.M=_.M||{};
(function(){var a=null;_.M.nb=function(b){var c="undefined"===typeof b;if(null!==a&&c)return a;var d={};b=b||window.location.href;var e=b.indexOf("?"),f=b.indexOf("#");b=(-1===f?b.substr(e+1):[b.substr(e+1,f-e-1),"&",b.substr(f+1)].join("")).split("&");for(var e=window.decodeURIComponent?window.decodeURIComponent:window.unescape,f=0,g=b.length;f<g;++f){var k=b[f].indexOf("=");if(-1!==k){var l=b[f].substring(0,k),k=b[f].substring(k+1),k=k.replace(/\+/g," ");try{d[l]=e(k)}catch(m){}}}c&&(a=d);return d}; _.M.nb()})();
(0,_.E)("gadgets.util.getUrlParameters",_.M.nb);
}catch(e){_._DumpException(e)}
try{
_.vc=window.console;_.wc=function(a){_.vc&&_.vc.log&&_.vc.log(a)};_.xc=function(){};
}catch(e){_._DumpException(e)}
try{
_.zc=function(){var a=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;a&&(0,_.fb)(a());return{register:function(a,c,d){d&&d((0,_.G)())},get:function(a){return(0,_.G)(a)},update:function(a,c){if(c)throw"Config replacement is not supported";(0,_.fb)(a)},$a:function(){}}}();
(0,_.E)("gadgets.config.register",_.zc.register);(0,_.E)("gadgets.config.get",_.zc.get);(0,_.E)("gadgets.config.init",_.zc.$a);(0,_.E)("gadgets.config.update",_.zc.update);
}catch(e){_._DumpException(e)}
try{
var Fc;
var Ac={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},Bc=function(a){var b,c,d;b=/[\"\\\x00-\x1f\x7f-\x9f]/g;if(void 0!==a){switch(typeof a){case "string":return b.test(a)?'"'+a.replace(b,function(a){var b=Ac[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)})+'"':'"'+a+'"';case "number":return(0,window.isFinite)(a)?String(a):"null";case "boolean":case "null":return String(a);case "object":if(!a)return"null";b=[];if("number"===
typeof a.length&&!a.propertyIsEnumerable("length")){d=a.length;for(c=0;c<d;c+=1)b.push(Bc(a[c])||"null");return"["+b.join(",")+"]"}for(c in a)!/___$/.test(c)&&(0,_.Na)(a,c)&&"string"===typeof c&&(d=Bc(a[c]))&&b.push(Bc(c)+":"+d);return"{"+b.join(",")+"}"}return""}},Cc=function(a){if(!a)return!1;if(/^[\],:{}\s]*$/.test(a.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}return!1}, Dc=!1;try{Dc=!!window.JSON&&'["a"]'===window.JSON.stringify(["a"])&&"a"===window.JSON.parse('["a"]')[0]}catch(Ec){}Fc=function(a){try{return window.JSON.parse(a)}catch(b){return!1}};_.Gc=Dc?window.JSON.stringify:Bc;_.Hc=Dc?Fc:Cc;

}catch(e){_._DumpException(e)}
try{
(0,_.E)("gadgets.json.stringify",_.Gc);(0,_.E)("gadgets.json.parse",_.Hc);(0,_.Sa)(_.Ga.location.href,"rpctoken")&&(0,_.Wa)(_.Ha,"unload",function(){});
}catch(e){_._DumpException(e)}
try{
var Mc;var Ic;Ic=function(){var a=_.Ha.readyState;return"complete"===a||"interactive"===a&&-1==window.navigator.userAgent.indexOf("MSIE")};_.Jc=function(a){if(Ic())a();else{var b=!1,c=function(){if(!b)return b=!0,a.apply(this,arguments)};_.Ga.addEventListener?(_.Ga.addEventListener("load",c,!1),_.Ga.addEventListener("DOMContentLoaded",c,!1)):_.Ga.attachEvent&&(_.Ga.attachEvent("onreadystatechange",function(){Ic()&&c.apply(this,arguments)}),_.Ga.attachEvent("onload",c))}};_.Kc=function(a,b){if(!Ic())try{a()}catch(c){}(0,_.Jc)(b)}; Mc=Mc||{};Mc.Bx=null;Mc.sw=null;Mc.hm=null;Mc.frameElement=null;
Mc=Mc||{};
Mc.Mr||(Mc.Mr=function(){function a(a){"undefined"!=typeof window.addEventListener?window.addEventListener("message",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onmessage",a);window.___jsl=window.___jsl||{};var b=window.___jsl;b.RPMQ=b.RPMQ||[];b.RPMQ.push(a)}function b(a){var b=(0,_.Hc)(a.data);if(b&&b.f){(0,_.rc)("gadgets.rpc.receive("+window.name+"): "+a.data);var d=_.N.Hh(b.f);e&&("undefined"!==typeof a.origin?a.origin!==d:a.domain!==/^.+:\/\/([^:]+).*/.exec(d)[1])?(0,_.Ib)("Invalid rpc message origin. "+
d+" vs "+(a.origin||"")):c(b,a.origin)}}var c,d,e=!0;return{hj:function(){return"wpm"},A:function(){return!0},$a:function(f,g){_.zc.register("rpc",null,function(a){"true"===String((a&&a.rpc||{}).disableForceSecure)&&(e=!1)});c=f;d=g;a(b);d("..",!0);return!0},ib:function(a){d(a,!0);return!0},call:function(a,b,c){var d=_.N.Hh(a),e=_.N.dt(a);d?window.setTimeout(function(){var a=(0,_.Gc)(c);(0,_.rc)("gadgets.rpc.send("+window.name+"): "+a);e.postMessage(a,d)},0):".."!=a&&(0,_.Ib)("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message"); return!0}}}());
Mc=Mc||{};
Mc.ul||(Mc.ul=function(){function a(a,b){I[b]=I[b]||function(){a.apply({},arguments)}}function b(){if(null===z&&window.document.body&&m){var a=m+"?cb="+Math.random()+"&origin="+H+"&jsl=1",c=window.document.createElement("div");c.style.height="1px";c.style.width="1px";a='<object height="1" width="1" id="'+l+'" type="application/x-shockwave-flash"><param name="allowScriptAccess" value="always"></param><param name="movie" value="'+a+'"></param><embed type="application/x-shockwave-flash" allowScriptAccess="always" src="'+a+
'" height="1" width="1"></embed></object>';window.document.body.appendChild(c);c.innerHTML=a;z=c.firstChild}++x;null!==v&&(null!==z||50<=x)?window.clearTimeout(v):v=window.setTimeout(b,100)}function c(){y[".."]||(k(".."),C++,50<=C&&null!==F?(window.clearTimeout(F),F=null):F=window.setTimeout(c,100))}function d(){if(null!==z&&z.setup)for(;0<w.length;){var a=w.shift(),b=a.WH;z.setup(a.yi,".."===b?_.N.Fn:b,".."===b?"INNER":"OUTER")}null!==v&&window.clearTimeout(v);v=null}function e(){y[".."]||null!==
F||(F=window.setTimeout(c,100))}function f(a,b,c){b=_.N.Hh(a);var d=_.N.ej(a);z["sendMessage_"+(".."===a?_.N.Fn:a)+"_"+d+"_"+(".."===a?"INNER":"OUTER")].call(z,(0,_.Gc)(c),b);return!0}function g(a,b){var c=(0,_.Hc)(a),d=c._scr;d?(t(d,!0),y[d]=!0,".."!==d&&k(d,!0)):window.setTimeout(function(){p(c,b)},0)}function k(a,b){var c=_.N.Fn,d={};d._scr=b?"..":c;d._pnt=c;f(a,0,d)}var l="___xpcswf",m=null,n=!1,p=null,t=null,z=null,w=[],v=null,x=0,C=0,F=null,y={},H=window.location.protocol+"//"+window.location.host,
I;window.___jsl=window.___jsl||{};I=window.___jsl._fm={};_.zc.register("rpc",null,function(a){n&&(m=a&&a.rpc&&a.rpc.commSwf||"//xpc.googleusercontent.com/gadgets/xpc.swf")});a(d,"ready");a(e,"setupDone");a(g,"receiveMessage");return{hj:function(){return"flash"},A:function(){return!0},$a:function(a,b){p=a;t=b;return n=!0},ib:function(a,c){w.push({yi:c,WH:a});null===z&&null===v&&(v=window.setTimeout(b,100));return!0},call:f,HB:g,D:d,F:e}}());
if(window.gadgets&&window.gadgets.rpc)"undefined"!=typeof _.N&&_.N||(_.N=window.gadgets.rpc,_.N.config=_.N.config,_.N.register=_.N.register,_.N.Yg=_.N.unregister,_.N.qx=_.N.registerDefault,_.N.Ty=_.N.unregisterDefault,_.N.bu=_.N.forceParentVerifiable,_.N.call=_.N.call,_.N.sj=_.N.getRelayUrl,_.N.Pe=_.N.setRelayUrl,_.N.Rm=_.N.setAuthToken,_.N.hk=_.N.setupReceiver,_.N.ej=_.N.getAuthToken,_.N.Gq=_.N.removeReceiver,_.N.Bu=_.N.getRelayChannel,_.N.ji=_.N.receive,_.N.mx=_.N.receiveSameDomain,_.N.va=_.N.getOrigin,
_.N.Hh=_.N.getTargetOrigin,_.N.dt=_.N._getTargetWin,_.N.GB=_.N._parseSiblingId);else{_.N=function(){function a(a,b){if(!Y[a]){var c=ya;b||(c=ja);Y[a]=c;for(var d=da[a]||[],e=0;e<d.length;++e){var f=d[e];f.t=F[a];c.call(a,f.f,f)}da[a]=[]}}function b(){function a(){sa=!0}wa||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onunload",a),wa=!0)}function c(a,c,d,e,f){F[c]&&F[c]===d||((0,_.Ib)("Invalid gadgets.rpc token. "+
F[c]+" vs "+d),Ka(c,2));f.onunload=function(){I[c]&&!sa&&(Ka(c,1),_.N.Gq(c))};b();e=(0,_.Hc)((0,window.decodeURIComponent)(e))}function d(b,c){if(b&&"string"===typeof b.s&&"string"===typeof b.f&&b.a instanceof Array)if(F[b.f]&&F[b.f]!==b.t&&((0,_.Ib)("Invalid gadgets.rpc token. "+F[b.f]+" vs "+b.t),Ka(b.f,2)),"__ack"===b.s)window.setTimeout(function(){a(b.f,!0)},0);else{b.c&&(b.callback=function(a){_.N.call(b.f,(b.g?"legacy__":"")+"__cb",null,b.c,a)});if(c){var d=e(c);b.origin=c;var f=b.r,g;try{g=
e(f)}catch(k){}f&&g==d||(f=c);b.referer=f}d=(v[b.s]||v[""]).apply(b,b.a);b.c&&"undefined"!==typeof d&&_.N.call(b.f,"__cb",null,b.c,d)}}function e(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");-1!=c&&(b=b.substring(0,c));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==
a)throw Error("b");var c="",d=b.indexOf(":");if(-1!=d){var e=b.substring(d+1),b=b.substring(0,d);if("http"===a&&"80"!==e||"https"===a&&"443"!==e)c=":"+e}return a+"://"+b+c}function f(a){if("/"==a.charAt(0)){var b=a.indexOf("|");return{id:0<b?a.substring(1,b):a.substring(1),origin:0<b?a.substring(b+1):null}}return null}function g(a){if("undefined"===typeof a||".."===a)return window.parent;var b=f(a);if(b)return window.top.frames[b.id];a=String(a);return(b=window.frames[a])?b:(b=window.document.getElementById(a))&&
b.contentWindow?b.contentWindow:null}function k(a,b){if(!0!==I[a]){"undefined"===typeof I[a]&&(I[a]=0);var c=g(a);".."!==a&&null==c||!0!==ya.ib(a,b)?!0!==I[a]&&10>I[a]++?window.setTimeout(function(){k(a,b)},500):(Y[a]=ja,I[a]=!0):I[a]=!0}}function l(a){(a=x[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a}function m(a,b,c){b&&!/http(s)?:\/\/.+/.test(b)&&(0==b.indexOf("//")?b=
window.location.protocol+b:"/"==b.charAt(0)?b=window.location.protocol+"//"+window.location.host+b:-1==b.indexOf("://")&&(b=window.location.protocol+"//"+b));x[a]=b;"undefined"!==typeof c&&(C[a]=!!c)}function n(a,b){b=b||"";F[a]=String(b);k(a,b)}function p(a){a=(a.passReferrer||"").split(":",2);X=a[0]||"none";xa=a[1]||"origin"}function t(b){"true"===String(b.useLegacyProtocol)&&(ya=Mc.hm||ja,ya.$a(d,a))}function z(a,b){function c(d){d=d&&d.rpc||{};p(d);var f=d.parentRelayUrl||"",f=e(Q.parent||b)+
f;m("..",f,"true"===String(d.useLegacyProtocol));t(d);n("..",a)}!Q.parent&&b?c({}):_.zc.register("rpc",null,c)}function w(a,b,c){if(".."===a)z(c||Q.rpctoken||Q.ifpctok||"",b);else t:{var d=null;if("/"!=a.charAt(0)){if(!_.M)break t;d=window.document.getElementById(a);if(!d)throw Error("c`"+a);}d=d&&d.src;b=b||_.N.va(d);m(a,b);b=_.M.nb(d);n(a,c||b.rpctoken)}}var v={},x={},C={},F={},y=0,H={},I={},Q={},Y={},da={},X=null,xa=null,S=window.top!==window.self,ka=window.name,Ka=function(){},$=window.console,
ea=$&&$.log&&function(a){$.log(a)}||function(){},ja=function(){function a(b){return function(){ea(b+": call ignored")}}return{getCode:function(){return"noop"},isParentVerifiable:function(){return!0},init:a("init"),setup:a("setup"),call:a("call")}}();_.M&&(Q=_.M.nb());var sa=!1,wa=!1,ya=function(){if("flash"==Q.rpctx)return Mc.ul;if("rmr"==Q.rpctx)return Mc.Bx;var a="function"===typeof window.postMessage?Mc.Mr:"object"===typeof window.postMessage?Mc.Mr:window.ActiveXObject?Mc.ul?Mc.ul:Mc.sw?Mc.sw:
Mc.hm:0<window.navigator.userAgent.indexOf("WebKit")?Mc.Bx:"Gecko"===window.navigator.product?Mc.frameElement:Mc.hm;a||(a=ja);return a}();v[""]=function(){ea("Unknown RPC service: "+this.s)};v.__cb=function(a,b){var c=H[a];c&&(delete H[a],c.call(this,b))};return{config:function(a){"function"===typeof a.Ix&&(Ka=a.Ix)},register:function(a,b){if("__cb"===a||"__ack"===a)throw Error("d");if(""===a)throw Error("e");v[a]=b},Yg:function(a){if("__cb"===a||"__ack"===a)throw Error("f");if(""===a)throw Error("g");
delete v[a]},qx:function(a){v[""]=a},Ty:function(){delete v[""]},bu:function(){},call:function(a,b,c,d){a=a||"..";var e="..";".."===a?e=ka:"/"==a.charAt(0)&&(e=_.N.va(window.location.href),e="/"+ka+(e?"|"+e:""));++y;c&&(H[y]=c);var g={s:b,f:e,c:c?y:0,a:Array.prototype.slice.call(arguments,3),t:F[a],l:!!C[a]},k;t:if("bidir"===X||"c2p"===X&&".."===a||"p2c"===X&&".."!==a){k=window.location.href;var l="?";if("query"===xa)l="#";else if("hash"===xa)break t;l=k.lastIndexOf(l);l=-1===l?k.length:l;k=k.substring(0,
l)}else k=null;k&&(g.r=k);if(".."===a||null!=f(a)||window.document.getElementById(a))(k=Y[a])||null===f(a)||(k=ya),0===b.indexOf("legacy__")&&(k=ya,g.s=b.substring(8),g.c=g.c?g.c:y),g.g=!0,g.r=e,k?(C[a]&&(k=Mc.hm),!1===k.call(a,e,g)&&(Y[a]=ja,ya.call(a,e,g))):da[a]?da[a].push(g):da[a]=[g]},sj:l,Pe:m,Rm:n,hk:w,ej:function(a){return F[a]},Gq:function(a){delete x[a];delete C[a];delete F[a];delete I[a];delete Y[a]},Bu:function(){return ya.hj()},ji:function(a,b){4<a.length?ya.HB(a,d):c.apply(null,a.concat(b))},
mx:function(a){a.a=Array.prototype.slice.call(a.a);window.setTimeout(function(){d(a)},0)},va:e,Hh:function(a){var b=null,c=l(a);c?b=c:(c=f(a))?b=c.origin:b=".."==a?Q.parent:window.document.getElementById(a).src;return e(b)},$a:function(){!1===ya.$a(d,a)&&(ya=ja);S?w(".."):_.zc.register("rpc",null,function(a){a=a.rpc||{};p(a);t(a)})},dt:g,GB:f,A:"__ack",Fn:ka||"..",D:0,C:1,B:2}}();_.N.$a()};
_.N.config({Ix:function(a){throw Error("h`"+a);}});_.rc=_.xc;(0,_.E)("gadgets.rpc.config",_.N.config);(0,_.E)("gadgets.rpc.register",_.N.register);(0,_.E)("gadgets.rpc.unregister",_.N.Yg);(0,_.E)("gadgets.rpc.registerDefault",_.N.qx);(0,_.E)("gadgets.rpc.unregisterDefault",_.N.Ty);(0,_.E)("gadgets.rpc.forceParentVerifiable",_.N.bu);(0,_.E)("gadgets.rpc.call",_.N.call);(0,_.E)("gadgets.rpc.getRelayUrl",_.N.sj);(0,_.E)("gadgets.rpc.setRelayUrl",_.N.Pe);(0,_.E)("gadgets.rpc.setAuthToken",_.N.Rm);(0,_.E)("gadgets.rpc.setupReceiver",_.N.hk);
(0,_.E)("gadgets.rpc.getAuthToken",_.N.ej);(0,_.E)("gadgets.rpc.removeReceiver",_.N.Gq);(0,_.E)("gadgets.rpc.getRelayChannel",_.N.Bu);(0,_.E)("gadgets.rpc.receive",_.N.ji);(0,_.E)("gadgets.rpc.receiveSameDomain",_.N.mx);(0,_.E)("gadgets.rpc.getOrigin",_.N.va);(0,_.E)("gadgets.rpc.getTargetOrigin",_.N.Hh);

}catch(e){_._DumpException(e)}
try{
_.M=_.M||{};_.M.Lk=function(a,b,c,d){"undefined"!=typeof a.addEventListener?a.addEventListener(b,c,d):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+b,c):(0,_.Kb)("cannot attachBrowserEvent: "+b)};_.M.AG=function(a){var b=window;b.removeEventListener?b.removeEventListener("mousemove",a,!1):b.detachEvent?b.detachEvent("onmousemove",a):(0,_.Kb)("cannot removeBrowserEvent: mousemove")};

}catch(e){_._DumpException(e)}
try{
_.Ob=function(){function a(){e[0]=1732584193;e[1]=4023233417;e[2]=2562383102;e[3]=271733878;e[4]=3285377520;n=m=0}function b(a){for(var b=g,c=0;64>c;c+=4)b[c/4]=a[c]<<24|a[c+1]<<16|a[c+2]<<8|a[c+3];for(c=16;80>c;c++)a=b[c-3]^b[c-8]^b[c-14]^b[c-16],b[c]=(a<<1|a>>>31)&4294967295;a=e[0];for(var d=e[1],f=e[2],k=e[3],l=e[4],m,n,c=0;80>c;c++)40>c?20>c?(m=k^d&(f^k),n=1518500249):(m=d^f^k,n=1859775393):60>c?(m=d&f|k&(d|f),n=2400959708):(m=d^f^k,n=3395469782),m=((a<<5|a>>>27)&4294967295)+m+l+n+b[c]&4294967295,
l=k,k=f,f=(d<<30|d>>>2)&4294967295,d=a,a=m;e[0]=e[0]+a&4294967295;e[1]=e[1]+d&4294967295;e[2]=e[2]+f&4294967295;e[3]=e[3]+k&4294967295;e[4]=e[4]+l&4294967295}function c(a,c){if("string"===typeof a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var d=[],e=0,g=a.length;e<g;++e)d.push(a.charCodeAt(e));a=d}c||(c=a.length);d=0;if(0==m)for(;d+64<c;)b(a.slice(d,d+64)),d+=64,n+=64;for(;d<c;)if(f[m++]=a[d++],n++,64==m)for(m=0,b(f);d+64<c;)b(a.slice(d,d+64)),d+=64,n+=64}function d(){var a=[],
d=8*n;56>m?c(k,56-m):c(k,64-(m-56));for(var g=63;56<=g;g--)f[g]=d&255,d>>>=8;b(f);for(g=d=0;5>g;g++)for(var l=24;0<=l;l-=8)a[d++]=e[g]>>l&255;return a}for(var e=[],f=[],g=[],k=[128],l=1;64>l;++l)k[l]=0;var m,n;a();return{reset:a,update:c,M:d,sf:function(){for(var a=d(),b="",c=0;c<a.length;c++)b+="0123456789ABCDEF".charAt(Math.floor(a[c]/16))+"0123456789ABCDEF".charAt(a[c]%16);return b}}};

}catch(e){_._DumpException(e)}
try{
_.Bd=function(){function a(a){var b=(0,_.Ob)();b.update(a);return b.sf()}var b=window.crypto;if(b&&"function"==typeof b.getRandomValues)return function(){var a=new window.Uint32Array(1);b.getRandomValues(a);return Number("0."+a[0])};var c=(0,_.G)("random/maxObserveMousemove");null==c&&(c=-1);var d=0,e=Math.random(),f=1,g=1E6*(window.screen.width*window.screen.width+window.screen.height),k=function(a){a=a||window.event;var b=a.screenX+a.clientX<<16,b=b+(a.screenY+a.clientY),b=(new Date).getTime()%
1E6*b;f=f*b%g;0<c&&++d==c&&_.M.AG(k)};0!=c&&_.M.Lk(window,"mousemove",k,!1);var l=a(window.document.cookie+"|"+window.document.location+"|"+(new Date).getTime()+"|"+e);return function(){var b=f,b=b+(0,window.parseInt)(l.substr(0,20),16);l=a(l);return b/(g+Math.pow(16,20))}}();
(0,_.E)("shindig.random",_.Bd);
}catch(e){_._DumpException(e)}
try{
_.Pb=function(a,b){return 0==a.lastIndexOf(b,0)};_.Qb=2147483648*Math.random()|0;_.J={};_.Rb=window.iframer={};
}catch(e){_._DumpException(e)}
try{
_.J.pa=_.J.pa||{};_.J.pa.ZB=function(a){try{return!!a.document}catch(b){}return!1};_.J.pa.Ju=function(a){var b=a.parent;return a!=b&&_.J.pa.ZB(b)?_.J.pa.Ju(b):a};_.J.pa.NP=function(a){var b=a.userAgent||"";a=a.product||"";return 0!=b.indexOf("Opera")&&-1==b.indexOf("WebKit")&&"Gecko"==a&&0<b.indexOf("rv:1.")};

}catch(e){_._DumpException(e)}
try{
var Dm;var hm=function(){_.J.Kv++;return["I",_.J.Kv,"_",(new Date).getTime()].join("")};var im=function(a){return a instanceof Array?a.join(","):a instanceof Object?(0,_.Gc)(a):a};var jm=function(){};var km=function(a){a&&a.match(lm)&&(0,_.fb)("googleapis.config/gcv",a)};var mm=function(a){_.Lb.Xn.xH(a)};var nm=function(a){_.Lb.Xn.Wq(a)};_.om=function(a,b){var c=b||{},d;for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);return c};
_.pm=function(a,b,c,d,e){var f=[],g;for(g in a)if(a.hasOwnProperty(g)){var k=b,l=c,m=a[g],n=d,p=qm(g);p[k]=p[k]||{};n=_.M.xm(n,m);m._iframe_wrapped_rpc_&&(n._iframe_wrapped_rpc_=!0);p[k][l]=n;f.push(g)}if(e)for(g in _.J.Ih)_.J.Ih.hasOwnProperty(g)&&f.push(g);return f.join(",")};var rm=function(a,b,c){var d={};if(a&&a._methods){a=a._methods.split(",");for(var e=0;e<a.length;e++){var f=a[e];d[f]=sm(f,b,c)}}return d};
var tm=function(a){if(a&&a.disableMultiLevelParentRelay)a=!1;else{var b;if(b=_.Rb&&_.Rb._open&&"inline"!=a.style&&!0!==a.inline)a=a.container,b=!(a&&("string"==typeof a&&window.document.getElementById(a)||window.document==(a.ownerDocument||a.document)));a=b}return a};var um=function(a,b){var c={},d=b.params||{},e;for(e in a)"#"==e.charAt(0)&&(c[e.substring(1)]=a[e]),0==e.indexOf("fr-")&&(c[e.substring(3)]=a[e]),"#"==d[e]&&(c[e]=a[e]);for(var f in c)delete a["fr-"+f],delete a["#"+f],delete a[f];return c};
var vm=function(a){if(":"==a.charAt(0)){var b=(0,_.G)("iframes/"+a.substring(1));a={};(0,_.uh)(b,a);(b=a.url)&&(a.url=(0,_.$h)(b));a.params||(a.params={});return a}return{url:(0,_.$h)(a)}};var wm=function(a){function b(){}b.prototype=xm.prototype;a.prototype=new b};var ym=function(a){return _.J.lk[a]};var zm=function(a,b){_.J.lk[a]=b};var Am=function(a){a=a||{};"auto"===a.height&&(a.height=_.jh.Eb());var b=window&&Bm&&Bm.ka();b?b.zx(a.width||0,a.height||0):_.Rb&&_.Rb._resizeMe&&_.Rb._resizeMe(a)};
var Cm=function(a){km(a)};Dm=function(a){var b=(0,_.Sa)(a.location.href,"urlindex");if(b=(0,_.La)(_.Ya,"fUrl",[])[b]){var c=a.location.hash,b=b+(/#/.test(b)?c.replace(/^#/,"&"):c);a.location.replace(b)}};_.Em=function(){return _.Ga.location.origin||_.Ga.location.protocol+"//"+_.Ga.location.host};
if(window.ToolbarApi)Bm=window.ToolbarApi,Bm.ka=window.ToolbarApi.getInstance,Bm.prototype=window.ToolbarApi.prototype,_.h=Bm.prototype,_.h.Lw=Bm.prototype.openWindow,_.h.Ct=Bm.prototype.closeWindow,_.h.ny=Bm.prototype.setOnCloseHandler,_.h.rt=Bm.prototype.canClosePopup,_.h.zx=Bm.prototype.resizeWindow;else{var Bm=function(){},Fm=null;Bm.ka=function(){!Fm&&window.external&&window.external.GTB_IsToolbar&&(Fm=new Bm);return Fm};_.h=Bm.prototype;_.h.Lw=function(a){return window.external.GTB_OpenPopup&&
window.external.GTB_OpenPopup(a)};_.h.Ct=function(a){window.external.GTB_ClosePopupWindow&&window.external.GTB_ClosePopupWindow(a)};_.h.ny=function(a,b){window.external.GTB_SetOnCloseHandler&&window.external.GTB_SetOnCloseHandler(a,b)};_.h.rt=function(a){return window.external.GTB_CanClosePopup&&window.external.GTB_CanClosePopup(a)};_.h.zx=function(a,b){return window.external.GTB_ResizeWindow&&window.external.GTB_ResizeWindow(a,b)};window.ToolbarApi=Bm;window.ToolbarApi.getInstance=Bm.ka};
var Gm=function(){_.N.register("_noop_echo",function(){this.callback(_.J.rD(_.J.Jf[this.f]))})},Hm=function(){window.setTimeout(function(){_.N.call("..","_noop_echo",_.J.iG)},0)},sm=function(a,b,c){var d=function(d){var f=Array.prototype.slice.call(arguments,0),g=f[f.length-1];if("function"===typeof g){var k=g;f.pop()}f.unshift(b,a,k,c);_.N.call.apply(_.N,f)};d._iframe_wrapped_rpc_=!0;return d},qm=function(a){_.J.Om[a]||(_.J.Om[a]={},_.N.register(a,function(b,c){var d=this.f;if(!("string"!=typeof b||
b in{}||d in{})){var e=this.callback,f=_.J.Om[a][d],g;f&&Object.hasOwnProperty.call(f,b)?g=f[b]:Object.hasOwnProperty.call(_.J.Ih,a)&&(g=_.J.Ih[a]);if(g)return d=Array.prototype.slice.call(arguments,1),g._iframe_wrapped_rpc_&&e&&d.push(e),g.apply({},d)}(0,_.Ib)(['Unregistered call in window "',window.name,'" for method "',a,'", via proxyId "',b,'" from frame "',d,'".'].join(""));return null}));return _.J.Om[a]};
_.J.YB=function(a,b,c){var d=Array.prototype.slice.call(arguments);_.J.yu(function(a){a.sameOrigin&&(d.unshift("/"+a.claimedOpenerId+"|"+window.location.protocol+"//"+window.location.host),_.N.call.apply(_.N,d))})};_.J.xG=function(a,b){_.N.register(a,b)};
var lm=/^[-_.0-9A-Za-z]+$/,Im={open:"open",onready:"ready",close:"close",onresize:"resize",onOpen:"open",onReady:"ready",onClose:"close",onResize:"resize",onRenderStart:"renderstart"},Jm={onBeforeParentOpen:"beforeparentopen"},Km={onOpen:function(a){var b=a.Ta();a.sd(b.container||b.element);return a},onClose:function(a){a.remove()}};_.J.nj=function(a){var b=(0,_.Ma)();(0,_.uh)(_.Oh,b);(0,_.uh)(a,b);return b};
var xm=function(a,b,c,d,e,f,g,k){this.config=vm(a);this.openParams=this.Vj=b||{};this.params=c||{};this.Ib=d;this.$m=!1;Lm(this,b.style);this.Wi={};Mm(this,function(){var a;(a=this.Vj.style)&&_.J.lk[a]?a=_.J.lk[a]:a?((0,_.Kb)(['Missing handler for style "',a,'". Continuing with default handler.'].join("")),a=null):a=Km;if(a){var b;if("function"===typeof a)b=a(this);else{var c={};for(b in a){var d=a[b];c[b]="function"===typeof d?_.M.xm(a,d,this):d}b=c}for(var g in e)a=b[g],"function"===typeof a&&Nm(this,
e[g],_.M.xm(b,a))}f&&Nm(this,"close",f)});this.nf=this.ac=g;this.qq=(k||[]).slice();g&&this.qq.unshift(g.da())};xm.prototype.Ta=function(){return this.Vj};xm.prototype.te=function(){return this.params};xm.prototype.El=function(){return this.Ib};xm.prototype.Bb=function(){return this.nf};var Lm=function(a,b){if(!a.$m){var c=b&&!_.J.lk[b]&&_.J.no[b];c?(a.mo=[],c(function(){a.$m=!0;for(var b=0,c=a.mo.length;b<c;++b)a.mo[b].call(a)})):a.$m=!0}},Mm=function(a,b){a.$m?b.call(a):a.mo.push(b)};
xm.prototype.Pb=function(a,b){Mm(this,function(){Nm(this,a,b)})};var Nm=function(a,b,c){a.Wi[b]=a.Wi[b]||[];a.Wi[b].push(c)};xm.prototype.Og=function(a,b){Mm(this,function(){var c=this.Wi[a];if(c)for(var d=0,e=c.length;d<e;++d)if(c[d]===b){c.splice(d,1);break}})};
xm.prototype.$d=function(a,b){var c,d=this.Wi[a];if(d)for(var e=Array.prototype.slice.call(arguments,1),f=0,g=d.length;f<g;++f)try{c=d[f].apply({},e)}catch(k){(0,_.Ib)(['Exception when calling callback "',a,'" with exception "',k.name,": ",k.message,'".'].join(""))}return c};
var Om=function(a){return"number"==typeof a?{value:a,Qo:a+"px"}:"100%"==a?{value:100,Qo:"100%",cw:!0}:null},Pm=function(a,b,c,d,e,f,g){xm.call(this,a,b,c,d,Im,e,f,g);this.id=b.id||hm();this.B=b.rpctoken&&String(b.rpctoken)||Math.round(1E9*(0,_.Bd)());this.D=um(this.params,this.config);this.Mo={};Mm(this,function(){this.$d("open");(0,_.om)(this.Mo,this)})};wm(Pm);_.h=Pm.prototype;
_.h.sd=function(a,b){if(!this.config.url)return(0,_.Ib)("Cannot open iframe, empty URL."),this;var c=this.id;_.J.Jf[c]=this;var d=(0,_.om)(this.Ib);d._ready=this.Em;d._close=this.close;d._open=this.rs;d._resizeMe=this.ss;d._renderstart=this.Gw;var e=this.D;this.B&&(e.rpctoken=this.B);e._methods=(0,_.pm)(d,c,"",this,!0);this.C=a="string"===typeof a?window.document.getElementById(a):a;d={};d.id=c;if(b){d.attributes=b;var f=b.style;if("string"===typeof f){var g;if(f){g=[];for(var f=f.split(";"),k=0,
l=f.length;k<l;++k){var m=f[k];if(0!=m.length||k+1!=l)m=m.split(":"),2==m.length&&m[0].match(/^[ a-zA-Z_-]+$/)&&m[1].match(/^[ +.%0-9a-zA-Z_-]+$/)?g.push(m.join(":")):(0,_.Ib)(['Iframe style "',f[k],'" not allowed.'].join(""))}g=g.join(";")}else g="";b.style=g}}this.Ta().allowPost&&(d.allowPost=!0);d.queryParams=this.params;d.fragmentParams=e;d.paramsSerializer=im;this.A=(0,_.bi)(this.config.url,a,d);e=this.A.getAttribute("data-postorigin")||this.A.src;_.J.Jf[c]=this;_.N.Rm(this.id,this.B);_.N.Pe(this.id,
e);return this};_.h.Ec=function(a,b){this.Mo[a]=b};_.h.da=function(){return this.id};_.h.Ca=function(){return this.A};_.h.Ja=function(){return this.C};_.h.Kd=function(a){this.C=a};_.h.Em=function(a){var b=rm(a,this.id,"");this.nf&&"function"==typeof this.Ib._ready&&(a._methods=(0,_.pm)(b,this.nf.da(),this.id,this,!1),this.Ib._ready(a));(0,_.om)(a,this);(0,_.om)(b,this);this.$d("ready",a)};_.h.Gw=function(a){this.$d("renderstart",a)};
_.h.close=function(a){a=this.$d("close",a);delete _.J.Jf[this.id];return a};_.h.remove=function(){var a=window.document.getElementById(this.id);a&&a.parentNode&&a.parentNode.removeChild(a)};
_.h.rs=function(a){var b=rm(a.params,this.id,a.proxyId);delete a.params._methods;"_parent"==a.openParams.anchor&&(a.openParams.anchor=this.C);if(tm(a.openParams))new Qm(a.url,a.openParams,a.params,b,b._onclose,this,a.openedByProxyChain);else{var c=new Pm(a.url,a.openParams,a.params,b,b._onclose,this,a.openedByProxyChain),d=this;Mm(c,function(){var a={childId:c.da()},f=c.Mo;f._toclose=c.close;a._methods=(0,_.pm)(f,d.id,c.id,c,!1);b._onopen(a)})}};
_.h.ss=function(a){if(void 0===this.$d("resize",a)&&this.A){var b=Om(a.width);null!=b&&(this.A.style.width=b.Qo);a=Om(a.height);null!=a&&(this.A.style.height=a.Qo);this.A.parentElement&&(null!=b&&b.cw||null!=a&&a.cw)&&(this.A.parentElement.style.display="block")}};
var Qm=function(a,b,c,d,e,f,g){xm.call(this,a,b,c,d,Jm,e,f,g);this.url=a;this.A=null;this.Aq=hm();Mm(this,function(){var a;this.$d("beforeparentopen");var b=(0,_.om)(this.Ib);b._onopen=this.dG;b._ready=this.Em;b._onclose=this.cG;this.params._methods=(0,_.pm)(b,"..",this.Aq,this,!0);b={};for(a in this.params)b[a]=im(this.params[a]);var c=this.config.url;if(this.Vj.hideUrlFromParent){a=window.name;var d=c,c=(0,_.Hh)(this.config.url,this.params,{},im),e=b,b={};b._methods=e._methods;b["#opener"]=e["#opener"];
b["#urlindex"]=e["#urlindex"];b["#opener"]&&void 0!=e["#urlindex"]?(b["#opener"]=a+","+b["#opener"],a=d):(d=(0,_.La)(_.Ya,"fUrl",[]),e=d.length,d[e]=c,_.Ya.rUrl=Dm,b["#opener"]=a,b["#urlindex"]=e,a=_.Lb.va(_.Ga.location.href),c=(0,_.G)("iframes/relay_url_"+(0,window.encodeURIComponent)(a))||"/_/gapi/sibling/1/frame.html",a=a+c);c=a}_.Rb._open({url:c,openParams:this.Vj,params:b,proxyId:this.Aq,openedByProxyChain:this.qq})})};wm(Qm);Qm.prototype.B=function(){return this.A};
Qm.prototype.dG=function(a){this.A=a.childId;var b=rm(a,"..",this.A);(0,_.om)(b,this);this.close=b._toclose;_.J.Jf[this.A]=this;this.nf&&this.Ib._onopen&&(a._methods=(0,_.pm)(b,this.nf.da(),this.A,this,!1),this.Ib._onopen(a))};Qm.prototype.Em=function(a){var b=String(this.A),c=rm(a,"..",b);(0,_.om)(a,this);(0,_.om)(c,this);this.$d("ready",a);this.nf&&this.Ib._ready&&(a._methods=(0,_.pm)(c,this.nf.da(),b,this,!1),this.Ib._ready(a))};
Qm.prototype.cG=function(a){if(this.nf&&this.Ib._onclose)this.Ib._onclose(a);else return a=this.$d("close",a),delete _.J.Jf[this.A],a};
var Rm=function(a,b,c,d,e,f,g){xm.call(this,a,b,c,d,Jm,f,g);this.id=b.id||hm();this.B=e;d._close=this.close;this.onClosed=this.A;this.cz=0;Mm(this,function(){this.$d("beforeparentopen");var b=(0,_.om)(this.Ib);this.params._methods=(0,_.pm)(b,"..",this.Aq,this,!0);b={};b.queryParams=this.params;a=(0,_.Th)(_.Ha,this.config.url,this.id,b);var c=e.Lw(a);this.canAutoClose=function(a){a(e.rt(c))};e.ny(c,this);this.cz=c})};wm(Rm);Rm.prototype.close=function(a){a=this.$d("close",a);this.B.Ct(this.cz);return a};
Rm.prototype.A=function(){this.$d("close")};
(function(){_.J.Jf={};_.J.lk={};_.J.no={};_.J.Kv=0;_.J.Om={};_.J.Ih={};_.J.Gm=null;_.J.Fm=[];_.J.iG=function(a){var b=!1;try{if(null!=a)var e=window.parent.frames[a.id],b=e.iframer.id==a.id&&e.iframes.openedId_(_.Rb.id)}catch(f){}try{_.J.Gm={origin:this.origin,referer:this.referer,claimedOpenerId:a&&a.id,claimedOpenerProxyChain:a&&a.proxyChain||[],sameOrigin:b};for(a=0;a<_.J.Fm.length;++a)_.J.Fm[a](_.J.Gm);_.J.Fm=[]}catch(g){}};_.J.rD=function(a){var b=a&&a.nf,e=null;b&&(e={},e.id=b.da(),e.proxyChain=
a.qq);return e};Gm();if(window.parent!=window){var a=_.M.nb();a.gcv&&km(a.gcv);var b=a.jsh;b&&mm(b);(0,_.om)(rm(a,"..",""),_.Rb);(0,_.om)(a,_.Rb);Hm()}_.J.ra=ym;_.J.kb=zm;_.J.wH=Cm;_.J.resize=Am;_.J.ZC=function(a){return _.J.no[a]};_.J.Zq=function(a,b){_.J.no[a]=b};_.J.yx=Am;_.J.GH=Cm;_.J.fm={};_.J.fm.get=ym;_.J.fm.set=zm;_.J.MB=function(a,b){qm(a);_.J.Ih[a]=b||window[a]};_.J.rP=function(a){delete _.J.Ih[a]};_.J.open=function(a,b,e,f,g,k){3==arguments.length?f={}:4==arguments.length&&"function"===
typeof f&&(g=f,f={});var l="bubble"===b.style&&Bm?Bm.ka():null;return l?new Rm(a,b,e,f,l,g,k):tm(b)?new Qm(a,b,e,f,g,k):new Pm(a,b,e,f,g,k)};_.J.close=function(a,b){_.Rb&&_.Rb._close&&_.Rb._close(a,b)};_.J.ready=function(a,b,e){2==arguments.length&&"function"===typeof b&&(e=b,b={});var f=a||{};"height"in f||(f.height=_.jh.Eb());f._methods=(0,_.pm)(b||{},"..","",_.Rb,!0);_.Rb&&_.Rb._ready&&_.Rb._ready(f,e)};_.J.yu=function(a){_.J.Gm?a(_.J.Gm):_.J.Fm.push(a)};_.J.fG=function(a){return!!_.J.Jf[a]};_.J.dD=
function(){return["https://ssl.gstatic.com/gb/js/",(0,_.G)("googleapis.config/gcv")].join("")};_.J.ix=function(a){var b={mouseover:1,mouseout:1};if(_.Rb._event)for(var e=0;e<a.length;e++){var f=a[e];f in b&&_.M.Lk(window.document,f,function(a){_.Rb._event({event:a.type,timestamp:(new Date).getTime()})},!0)}};_.J.yH=mm;_.J.Wq=nm;_.J.kw=jm;_.J.Qv=_.Rb})();
(0,_.E)("iframes.allow",_.J.MB);(0,_.E)("iframes.callSiblingOpener",_.J.YB);(0,_.E)("iframes.registerForOpenedSibling",_.J.xG);(0,_.E)("iframes.close",_.J.close);(0,_.E)("iframes.getGoogleConnectJsUri",_.J.dD);(0,_.E)("iframes.getHandler",_.J.ra);(0,_.E)("iframes.getDeferredHandler",_.J.ZC);(0,_.E)("iframes.getParentInfo",_.J.yu);(0,_.E)("iframes.iframer",_.J.Qv);(0,_.E)("iframes.open",_.J.open);(0,_.E)("iframes.openedId_",_.J.fG);(0,_.E)("iframes.propagate",_.J.ix);(0,_.E)("iframes.ready",_.J.ready);
(0,_.E)("iframes.resize",_.J.resize);(0,_.E)("iframes.setGoogleConnectJsVersion",_.J.wH);(0,_.E)("iframes.setBootstrapHint",_.J.Wq);(0,_.E)("iframes.setJsHint",_.J.yH);(0,_.E)("iframes.setHandler",_.J.kb);(0,_.E)("iframes.setDeferredHandler",_.J.Zq);(0,_.E)("IframeBase",xm);(0,_.E)("IframeBase.prototype.addCallback",xm.prototype.Pb);(0,_.E)("IframeBase.prototype.getMethods",xm.prototype.El);(0,_.E)("IframeBase.prototype.getOpenerIframe",xm.prototype.Bb);
(0,_.E)("IframeBase.prototype.getOpenParams",xm.prototype.Ta);(0,_.E)("IframeBase.prototype.getParams",xm.prototype.te);(0,_.E)("IframeBase.prototype.removeCallback",xm.prototype.Og);(0,_.E)("Iframe",Pm);(0,_.E)("Iframe.prototype.close",Pm.prototype.close);(0,_.E)("Iframe.prototype.exposeMethod",Pm.prototype.Ec);(0,_.E)("Iframe.prototype.getId",Pm.prototype.da);(0,_.E)("Iframe.prototype.getIframeEl",Pm.prototype.Ca);(0,_.E)("Iframe.prototype.getSiteEl",Pm.prototype.Ja);
(0,_.E)("Iframe.prototype.openInto",Pm.prototype.sd);(0,_.E)("Iframe.prototype.remove",Pm.prototype.remove);(0,_.E)("Iframe.prototype.setSiteEl",Pm.prototype.Kd);(0,_.E)("Iframe.prototype.addCallback",Pm.prototype.Pb);(0,_.E)("Iframe.prototype.getMethods",Pm.prototype.El);(0,_.E)("Iframe.prototype.getOpenerIframe",Pm.prototype.Bb);(0,_.E)("Iframe.prototype.getOpenParams",Pm.prototype.Ta);(0,_.E)("Iframe.prototype.getParams",Pm.prototype.te);(0,_.E)("Iframe.prototype.removeCallback",Pm.prototype.Og);
(0,_.E)("IframeProxy",Qm);(0,_.E)("IframeProxy.prototype.getTargetIframeId",Qm.prototype.B);(0,_.E)("IframeProxy.prototype.addCallback",Qm.prototype.Pb);(0,_.E)("IframeProxy.prototype.getMethods",Qm.prototype.El);(0,_.E)("IframeProxy.prototype.getOpenerIframe",Qm.prototype.Bb);(0,_.E)("IframeProxy.prototype.getOpenParams",Qm.prototype.Ta);(0,_.E)("IframeProxy.prototype.getParams",Qm.prototype.te);(0,_.E)("IframeProxy.prototype.removeCallback",Qm.prototype.Og);(0,_.E)("IframeWindow",Rm);
(0,_.E)("IframeWindow.prototype.close",Rm.prototype.close);(0,_.E)("IframeWindow.prototype.onClosed",Rm.prototype.A);(0,_.E)("iframes.util.getTopMostAccessibleWindow",_.J.pa.Ju);(0,_.E)("iframes.handlers.get",_.J.fm.get);(0,_.E)("iframes.handlers.set",_.J.fm.set);(0,_.E)("iframes.resizeMe",_.J.yx);(0,_.E)("iframes.setVersionOverride",_.J.GH);
xm.prototype.send=function(a,b,c){_.J.Ox(this,a,b,c)};_.Rb.send=function(a,b,c){_.J.Ox(_.Rb,a,b,c)};xm.prototype.register=function(a,b){var c=this;c.Pb(a,function(a){b.call(c,a)})};_.J.Ox=function(a,b,c,d){var e=[];void 0!==c&&e.push(c);d&&e.push(function(a){d.call(this,[a])});a[b]&&a[b].apply(a,e)};_.J.qf=function(){return!0};(0,_.E)("iframes.CROSS_ORIGIN_IFRAMES_FILTER",_.J.qf);(0,_.E)("IframeBase.prototype.send",xm.prototype.send);(0,_.E)("IframeBase.prototype.register",xm.prototype.register);
(0,_.E)("Iframe.prototype.send",Pm.prototype.send);(0,_.E)("Iframe.prototype.register",Pm.prototype.register);(0,_.E)("IframeProxy.prototype.send",Qm.prototype.send);(0,_.E)("IframeProxy.prototype.register",Qm.prototype.register);(0,_.E)("IframeWindow.prototype.send",Rm.prototype.send);(0,_.E)("IframeWindow.prototype.register",Rm.prototype.register);(0,_.E)("iframes.iframer.send",_.J.Qv.send);

}catch(e){_._DumpException(e)}
try{
_.Mb=window.googleapis&&window.googleapis.server||{};
}catch(e){_._DumpException(e)}
try{
_.M=_.M||{};
(function(){function a(b){var c="";if(3==b.nodeType||4==b.nodeType)c=b.nodeValue;else if(b.innerText)c=b.innerText;else if(b.innerHTML)c=b.innerHTML;else if(b.firstChild){c=[];for(b=b.firstChild;b;b=b.nextSibling)c.push(a(b));c=c.join("")}return c}_.M.createElement=function(a){var c;if(!window.document.body||window.document.body.namespaceURI)try{c=window.document.createElementNS("http://www.w3.org/1999/xhtml",a)}catch(d){}return c||window.document.createElement(a)};_.M.ko=function(a){var c=_.M.createElement("iframe");
try{var d=["<","iframe"],e=a||{},f;for(f in e)e.hasOwnProperty(f)&&(d.push(" "),d.push(f),d.push('="'),d.push(_.M.pl(e[f])),d.push('"'));d.push("></");d.push("iframe");d.push(">");var g=_.M.createElement(d.join(""));g&&(!c||g.tagName==c.tagName&&g.namespaceURI==c.namespaceURI)&&(c=g)}catch(k){}d=c;a=a||{};for(var l in a)a.hasOwnProperty(l)&&(d[l]=a[l]);return c};_.M.hu=function(){if(window.document.body)return window.document.body;try{var a=window.document.getElementsByTagNameNS("http://www.w3.org/1999/xhtml", "body");if(a&&1==a.length)return a[0]}catch(c){}return window.document.documentElement||window.document};_.M.CP=function(b){return a(b)}})();

}catch(e){_._DumpException(e)}
try{
_.Nb=function(){var a=/\s*;\s*/;return{get:function(b,c){for(var d=b+"=",e=(window.document.cookie||"").split(a),f=0,g;g=e[f];++f)if(0==g.indexOf(d))return g.substr(d.length);return c}}}();
}catch(e){_._DumpException(e)}
try{
_.K=function(a,b){return _.ba[a]=b};_.Sb=function(a){return"function"==(0,_.ia)(a)};_.Tb=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.Ub=function(a){return"number"==typeof a};
}catch(e){_._DumpException(e)}
try{
var ec;var dc;var bc;var ac;var $b;var Zb;var Yb;_.Vb=function(a){var b=(0,_.ia)(a);return"array"==b||"object"==b&&"number"==typeof a.length};Yb=/[&<>"']/;Zb=/'/g;$b=/"/g;ac=/>/g;bc=/</g;dc=/&/g;ec=0;_.fc=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};
_.gc=function(a){if(!Yb.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(dc,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(bc,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ac,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace($b,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Zb,"&#39;"));return a};_.hc=function(a){return a[_.ra]||(a[_.ra]=++ec)};_.ic=Array.prototype;
_.jc=_.ic.indexOf?function(a,b,c){return _.ic.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if((0,_.pa)(a))return(0,_.pa)(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.kc=_.ic.forEach?function(a,b,c){_.ic.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=(0,_.pa)(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.lc=_.ic.filter?function(a,b,c){return _.ic.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=(0,_.pa)(a)?a.split(""):a,k=0;k<d;k++)if(k in g){var l=g[k];b.call(c,l,k,a)&&(e[f++]=l)}return e};_.mc=_.ic.map?function(a,b,c){return _.ic.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=(0,_.pa)(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
_.nc=_.ic.some?function(a,b,c){return _.ic.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=(0,_.pa)(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.oc=_.ic.every?function(a,b,c){return _.ic.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=(0,_.pa)(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};_.pc=function(a,b){return 0<=(0,_.jc)(a,b)};

}catch(e){_._DumpException(e)}
try{
_.qc=function(){function a(){var a=window.__OVERRIDE_SID;null==a&&(a=_.Nb.get("SID"));return!!a}function b(a,b,f){if(1==((0,_.ma)(f)?2:1))return c([b,a].join(" "));var g=[],k=[];(0,_.kc)(f,function(a){k.push(a.key);g.push(a.value)});f=(new Date).getTime();var l=[],l=0==g.length?[f,b,a]:[g.join(":"),f,b,a];a=c(l.join(" "));a=[f,a];0==k.length||a.push(k.join(""));return a.join("_")}function c(a){var b=(0,_.Ob)();b.update(a);return b.sf().toLowerCase()}return{Mp:function(a){var b={SAPISIDHASH:!0,APISIDHASH:!0};
return a&&(a.OriginToken||a.Authorization&&b[String(a.Authorization).split(" ")[0]])?!0:!1},xF:a,tD:function(){var b=null;a()&&(b=window.__PVT,null==b&&(b=_.Nb.get("BEAT")));return b},xl:function(c){var e=_.Lb.va(String(window.location.href));if(a()){var f=0==e.indexOf("https:")||0==e.indexOf("chrome-extension:"),g=f?window.__SAPISID:window.__APISID;null==g&&(g=_.Nb.get(f?"SAPISID":"APISID"));if(g)return[f?"SAPISIDHASH":"APISIDHASH",b(e,g,c)].join(" ")}return null}}}();

}catch(e){_._DumpException(e)}
try{
_.Zc=function(){return Math.floor((new Date).getTime()/1E3)};var bd;var ad;_.$c=function(a,b){this.A=a;var c=b||{};this.D=c.JF;this.B=c.domain;this.C=c.path;this.F=c.dH};ad=/^[-+/_=.:|%&a-zA-Z0-9@]*$/;bd=/^[A-Z_][A-Z0-9_]{0,63}$/;_.$c.prototype.Ng=function(){for(var a=this.A+"=",b=window.document.cookie.split(/;\s*/),c=0;c<b.length;++c){var d=b[c];if(0==d.indexOf(a))return d.substr(a.length)}};
_.$c.prototype.write=function(a,b){if(!bd.test(this.A))throw"Invalid cookie name";if(!ad.test(a))throw"Invalid cookie value";var c=this.A+"="+a;this.B&&(c+=";domain="+this.B);this.C&&(c+=";path="+this.C);var d="number"===typeof b?b:this.D;if(0<=d){var e=new Date;e.setSeconds(e.getSeconds()+d);c+=";expires="+e.toUTCString()}this.F&&(c+=";secure");window.document.cookie=c};_.$c.prototype.clear=function(){this.write("",0)}; _.$c.iterate=function(a){for(var b=window.document.cookie.split(/;\s*/),c=0;c<b.length;++c){var d=b[c].split("="),e=d.shift();a(e,d.join("="))}};
var dd;_.cd=function(a){this.A=a};dd={};_.cd.prototype.Ng=function(){if(dd.hasOwnProperty(this.A))return dd[this.A]};_.cd.prototype.write=function(a){dd[this.A]=a};_.cd.prototype.clear=function(){delete dd[this.A]};_.cd.iterate=function(a){for(var b in dd)dd.hasOwnProperty(b)&&a(b,dd[b])};
_.ed=function(a){this.B=a;this.A=window.sessionStorage};_.ed.prototype.Ng=function(){return this.A&&this.A.getItem(this.B)};_.ed.prototype.write=function(a){this.A&&this.A.setItem(this.B,a)};_.ed.prototype.clear=function(){this.A&&this.A.removeItem(this.B)};_.ed.iterate=function(a){if(window.sessionStorage)for(var b=0,c=window.sessionStorage.length;b<c;++b){var d=window.sessionStorage.key(b);a(d,window.sessionStorage[d])}};
for(var fd=0;64>fd;++fd);var gd;gd=[".APPS.GOOGLEUSERCONTENT.COM","@DEVELOPER.GSERVICEACCOUNT.COM"];_.id="https:"===window.location.protocol;_.jd=_.id||"http:"===window.location.protocol?_.$c:_.cd;_.kd=function(a){a=a.toUpperCase();for(var b=0,c=gd.length;b<c;++b){var d=a.split(gd[b]);2==d.length&&""===d[1]&&(a=d[0])}a=a.replace(/-/g,"_").toUpperCase();40<a.length&&(b=new _.Yc,b.Br(a),a=b.sf().toUpperCase());return a};
_.ld=function(a){var b=a.substr(1),c="",d=window.location.hostname;if(""!==b){c=(0,window.parseInt)(b,10);if((0,window.isNaN)(c))return null;b=d.split(".");if(b.length<c-1)return null;b.length==c-1&&(d="."+d)}else d="";return{vb:"S"==a.charAt(0),domain:d,wd:c}};
_.md=function(a){if(0!==a.indexOf("GCSC"))return null;var b={mc:!1};a=a.substr(4);if(!a)return b;var c=a.charAt(0);a=a.substr(1);var d=a.lastIndexOf("_");if(-1==d)return b;var e=(0,_.ld)(a.substr(d+1));if(null==e)return b;a=a.substring(0,d);if("_"!==a.charAt(0))return b;d="E"===c&&e.vb;return!d&&("U"!==c||e.vb)||d&&!_.id?b:{mc:!0,vb:d,zt:a.substr(1),domain:e.domain,wd:e.wd}};
var wd;var td;var sd;var od;var nd;nd=(0,_.Ma)();od=(0,_.Ma)();_.pd=(0,_.Ma)();_.qd=(0,_.Ma)();_.rd=null;sd="state code cookie_policy g_user_cookie_policy authuser prompt g-oauth-window status".split(" ");td=function(a){this.B=a;this.A=null};td.prototype.write=function(a){var b=(0,_.Ma)(),c=(0,_.Ma)(),d;for(d in a)(0,_.Na)(a,d)&&(c[d]=a[d],b[d]=a[d]);d=0;for(var e=sd.length;d<e;++d)delete c[sd[d]];a=String(a.authuser||0);d=(0,_.Ma)();d[a]=_.M.nb("#"+(0,_.ud)(c));this.B.write((0,_.Gc)(d));this.A=b};
td.prototype.Ng=function(){return this.A};td.prototype.clear=function(){this.B.clear();this.A=(0,_.Ma)()};
_.vd=function(a){if(!a)return null;"single_host_origin"!==a&&(a=_.N.va(a));var b=window.location.hostname,c=b,d=_.id;if("single_host_origin"!==a){c=a.split("://");if(2==c.length)d="https"===c.shift();else return(0,_.wc)("WARNING invalid cookie_policy: "+a),null;c=c[0]}if(-1!==c.indexOf(":"))c=b="";else{a="."+c;if(b.lastIndexOf(a)!==b.length-a.length)return(0,_.wc)("Invalid cookie_policy domain: "+c),null;c=a;b=c.split(".").length-1}return{domain:c,vb:d,wd:b}};
wd=function(a){if(!a)return null;var b=a.client_id;if(!b)return null;b=(0,_.kd)(b);a=(0,_.vd)(a.cookie_policy);return a?!_.id&&a.vb?((0,_.wc)("WARNING: https cookie_policy set for http domain"),null):["GCSC",a.vb?"E":"U","_",b,"_",a.vb?"S":"H",a.wd].join(""):null};_.xd=function(a){return a?{domain:a.domain,path:"/",dH:a.vb}:null};_.yd=function(a){var b=nd[a];b||(b=new td(new _.cd(a)),nd[a]=b);return{Wg:b,key:a}};
_.zd=function(a,b){var c=b?od:nd,d=b?_.jd:_.ed,e=a&&wd(a),f=!!e;a&&!a.g_user_cookie_policy&&(d=_.cd,e="token");if(!e)if(!b&&_.rd)e=_.rd;else return null;var g=c[e];if(!g){g=(0,_.md)(e);if(!("token"===e||g&&g.mc))return null;g=new d(e,(0,_.xd)(g));b||(g=new td(g))}c[e]=g;return{Wg:g,key:e,MC:f}};
_.Ad=function(a,b,c){a=a&&"token"!==a?(0,_.yd)(a):(0,_.zd)();if(!a)return null;if(c){c=a.Wg;(0,_.Ma)();var d=c.B.Ng();c=null;try{c=(0,_.Hc)(d)}catch(e){}!1==c&&(c=null);d=(0,_.Qc)()||"0";d=String(d);c=c&&c[d]}else c=a.Wg.Ng();c&&c.expires_at&&(0,_.Zc)()>c.expires_at&&(a.Wg.clear(),c=null);c&&c.error&&!b&&(c=null);return c};
_.ud=function(a){var b="";if(!a)return b;for(var c in a)if({}.hasOwnProperty.call(a,c)){var d;d=a[c];if(null!=d){var e=[(0,window.encodeURIComponent)(c),"="];if(d instanceof Array){for(var f=[],g=0;g<d.length;g++)f.push((0,window.encodeURIComponent)(d[g]));e.push(f.join("+"))}else e.push((0,window.encodeURIComponent)(d));d=e.join("")}else d="";d&&(b&&(b+="&"),b+=d)}return b};_.ed.iterate(function(a){var b=(0,_.md)(a);b&&b.mc&&(nd[a]=new td(new _.ed(a)))}); _.jd.iterate(function(a){nd[a]&&(od[a]=new _.jd(a,(0,_.xd)((0,_.md)(a))))});

}catch(e){_._DumpException(e)}
try{
var Ed;_.Cd=function(a,b,c){return 2>=arguments.length?_.ic.slice.call(a,b):_.ic.slice.call(a,b,c)};_.Dd=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};Ed=function(a,b){return a<b?-1:a>b?1:0};_.Hd=function(a,b){return-1!=a.indexOf(b)};_.Id=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
_.Jd=function(a,b){for(var c=0,d=(0,_.Dd)(String(a)).split("."),e=(0,_.Dd)(String(b)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var k=d[g]||"",l=e[g]||"",m=RegExp("(\\d*)(\\D*)","g"),n=RegExp("(\\d*)(\\D*)","g");do{var p=m.exec(k)||["","",""],t=n.exec(l)||["","",""];if(0==p[0].length&&0==t[0].length)break;c=Ed(0==p[1].length?0:(0,window.parseInt)(p[1],10),0==t[1].length?0:(0,window.parseInt)(t[1],10))||Ed(0==p[2].length,0==t[2].length)||Ed(p[2],t[2])}while(0==c)}return c};_.Kd=function(){}; t:{var Md=_.r.navigator;if(Md){var Nd=Md.userAgent;if(Nd){_.Ld=Nd;break t}}_.Ld=""}_.Od=function(a){return(0,_.Hd)(_.Ld,a)};
var ke;var ge;var ee;var be;var ae;var Wd;Wd=function(){return _.r.navigator||null};_.Xd=(0,_.Od)("Opera")||(0,_.Od)("OPR");_.O=(0,_.Od)("Trident")||(0,_.Od)("MSIE");_.Yd=(0,_.Od)("Gecko")&&!(0,_.Hd)(_.Ld.toLowerCase(),"webkit")&&!((0,_.Od)("Trident")||(0,_.Od)("MSIE"));_.Zd=(0,_.Hd)(_.Ld.toLowerCase(),"webkit");_.$d=_.Zd&&(0,_.Od)("Mobile");ae=Wd();be=ae&&ae.platform||"";_.Pd=(0,_.Hd)(be,"Mac");_.Qd=(0,_.Hd)(be,"Win");_.Rd=(0,_.Hd)(be,"Linux");_.Td=!!Wd()&&(0,_.Hd)(Wd().appVersion||"","X11");
var ce=_.Ld;_.Ud=!!ce&&(0,_.Hd)(ce,"Android");_.Vd=!!ce&&(0,_.Hd)(ce,"iPhone");_.de=!!ce&&(0,_.Hd)(ce,"iPad");ee=function(){var a=_.r.document;return a?a.documentMode:void 0};_.fe=function(){var a="",b;if(_.Xd&&_.r.opera)return a=_.r.opera.version,(0,_.Sb)(a)?a():a;_.Yd?b=/rv\:([^\);]+)(\)|;)/:_.O?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:_.Zd&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(_.Ld))?a[1]:"");return _.O&&(b=ee(),b>(0,window.parseFloat)(a))?String(b):a}();ge={}; _.he=function(a){return ge[a]||(ge[a]=0<=(0,_.Jd)(_.fe,a))};_.je=function(a){return _.O&&_.ie>=a};ke=_.r.document;_.ie=ke&&_.O?ee()||("CSS1Compat"==ke.compatMode?(0,window.parseInt)(_.fe,10):5):void 0;

}catch(e){_._DumpException(e)}
try{
var qe;var pe;var le;le=function(a){return Array.prototype.join.call(arguments,"")};_.me=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};_.oe=function(a,b,c,d,e,f,g){var k="";a&&(k+=a+":");c&&(k+="//",b&&(k+=b+"@"),k+=c,d&&(k+=":"+d));e&&(k+=e);f&&(k+="?"+f);g&&(k+="#"+g);return k};pe=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");
_.re=function(a){if(qe){qe=!1;var b=_.r.location;if(b){var c=b.href;if(c&&(c=(c=(0,_.re)(c)[3]||null)&&(0,window.decodeURIComponent)(c))&&c!=b.hostname)throw qe=!0,Error();}}return a.match(pe)};qe=_.Zd;_.se=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};
_.te=function(a,b,c){if((0,_.ma)(b))for(var d=0;d<b.length;d++)(0,_.te)(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",(0,window.encodeURIComponent)(String(b)))};_.ue=function(a,b){for(var c in b)(0,_.te)(c,b[c],a);return a};_.ve=function(a,b){(0,_.me)(a,"/")&&(a=a.substr(0,a.length-1));(0,_.Pb)(b,"/")&&(b=b.substr(1));return le(a,"/",b)};

}catch(e){_._DumpException(e)}
try{
var we;we=function(a,b){var c=_.M.ko({id:a,name:a});c.style.width="1px";c.style.height="1px";c.style.position="absolute";c.style.top="-100px";var d;if(window.navigator){d=window.navigator.userAgent||"";var e=window.navigator.product||"";d=0!=d.indexOf("Opera")&&-1==d.indexOf("WebKit")&&"Gecko"==e&&0<d.indexOf("rv:1.")}else d=!1;c.src=d?"about:blank":b;c.tabIndex="-1";window.document.body.appendChild(c);d&&(c.src=b);return c};
_.xe=function(){function a(a,b,c){for(var d=(new Date).getTime(),e=0;e<t.length;e++){var f=t[e];window.setTimeout(function(){f(a,d,b,c)},1)}}function b(a,b,c,d){var e=k("proxy");if(c||!e)var e=k("root"),f=k("root-1p")||e,g=k("xd3"),e=(c||String(b?f:e))+g;(b=_.M.nb().jsh||_.Lb.Xn.su())&&(e+=(0<=e.indexOf("?")?"&":"?")+"jsh="+(0,window.encodeURIComponent)(b));k("push")&&(e+=(0<=e.indexOf("?")?"&":"?")+"p=1");e+="#parent="+(0,window.encodeURIComponent)(null!=d?String(d):_.Lb.va(window.document.location.href));
return e+("&rpctoken="+a)}function c(b,c,d,g){var k=e(d,g);if(!m[k]){var l=we(k,c);_.N.register("ready:"+b,function(){_.N.Yg("ready:"+b);if(!n[k]){n[k]=!0;var c=p[k];p[k]=[];for(var e=0,l=c.length;e<l;++e){var m=c[e];f(m.ak,m.IG,m.Cc)}a("ready",d,g||null)}});_.N.hk(k,c);m[k]=l}}function d(d,e){var f=String(2147483647*(0,_.Bd)()|0),g=b(f,d,e);a("loading",d,e||null);(0,_.Jc)(function(){c(f,g,d,e)})}function e(a,c){var d=b("",a,c,""),e=l[d];e||(e=(0,_.Ob)(),e.update(d),e=e.sf().toLowerCase(),e+=Math.random(),
l[d]=e);return"apiproxy"+e}function f(a,b,c){var f=null,k=!1,l=function(a){a&&(f=a.root||f,k=_.qc.Mp(a.headers))};if("makeRequest"===a||"listen"===a)l(b);else if("makeHttpRequests"===a&&b){for(var t=(0,_.G)("client/jsonpOverride"),H=0,I=b.length;H<I;++H){var Q=b[H];Q&&(Q=Q.params,l(Q),t&&g(Q,c))}if(t)return}l=e(k,f);m[l]||d(k,f);n[l]?_.N.call(l,a,function(b){var d=(0,_.Hc)(b);if("makeRequest"==a&&d){for(var e={},f=0;f<d.length;f++)e[d[f].id]=d[f];c(e,b)}else c(d,b)},b):(p[l]||(p[l]=[]),p[l].push({ak:a,
IG:b,Cc:c}))}function g(a,b){if("GET"!=a.httpMethod)throw"JSONP supports GET methods only.";var c="jpcb"+String(2147483647*(0,_.Bd)()|0),d=window.document.createElement("script"),e=window.document.getElementsByTagName("head")[0];window[c]=function(a){b(a);try{delete window[c]}catch(f){window[c]=void 0}window.setTimeout(function(){e.removeChild(d)},1)};var f=a.root||k("root"),g=a.urlParams;g.callback=c;f=(0,_.ve)(f,a.url);g=(0,_.se)((0,_.ue)([f],g));d.setAttribute("id",c);d.setAttribute("src",g);d.setAttribute("charset",
"utf-8");e.appendChild(d)}function k(a){return(0,_.G)("googleapis.config/"+a)}var l={},m={},n={},p={},t=[];return{Qi:function(a,b){var c=a||{},d=b||window.location.href,e=c.Authorization,f=c.OriginToken;if(!e&&!f){(f=(0,_.Ad)(void 0,void 0))&&f.access_token&&(e=String(f.token_type||"Bearer")+" "+f.access_token);if(!e&&k("auth/useFirstPartyAuth")&&_.qc.xF()){f=c["X-Goog-AuthUser"];null==f&&(f=_.google.jp(d)||"0");if(k("auth/useFirstPartyAuthV2")){var d=k("primaryEmail"),e=k("appDomain"),g=k("fogId"),
l=[];d&&l.push({key:"e",value:d});e&&l.push({key:"a",value:e});g&&l.push({key:"u",value:g});e=_.qc.xl(l)}else e=_.qc.xl();e&&(c["X-Goog-AuthUser"]=f)}e?c.Authorization=e:!1!==k("auth/useOriginToken")&&(f=_.qc.tD())&&(c.OriginToken=f)}return c},KB:function(a){t.push(a)},A:g,CG:function(a){for(var b=0;b<t.length;b++)if(t[b]==a){t.splice(b,1);break}},Me:f}}();

}catch(e){_._DumpException(e)}
try{
var ___;_.vf=window.tamings___||[];_.wf=window.caja___;___=window.___;
}catch(e){_._DumpException(e)}
try{
_.Ea.Uj=function(){var a={},b=[],c=function(a){var b={method:a.request.method,id:a.key};a.request.rpc&&(b.params=a.request.rpc);return b};a.execute=function(a){for(var e={},f={},g=0,k=[],l=0;l<b.length;l++){var m=b[l].request.transport;f[m.name]||(k.push(m),g++);f[m.name]=f[m.name]||[];f[m.name].push(c(b[l]))}l=function(c){c.error&&(e.error=c.error);for(var f=0;f<b.length;f++){var k=b[f].key,l=c[k];l&&(e[k]=l.error?l:l.data||l.result)}g--;0===g&&a(e)};for(m=0;m<k.length;m++)k[m].execute(f[k[m].name], l);0==g&&window.setTimeout(function(){a(e)},0)};a.add=function(c,e){e&&c&&b.push({key:c,request:e});return a};return a};
_.Ea.Gk=function(a,b){if("newBatch"!==a){for(var c=a.split("."),d=window.osapi,e=0;e<c.length-1;e++)d[c[e]]=d[c[e]]||{},d=d[c[e]];var f=c[c.length-1];d[f]?(d.__dupwarn||(0,_.Kb)("Skipping duplicate osapi method definition "+a+" on transport "+b.name+"; others may exist, but suppressing warnings"),d.__dupwarn=!0):(d[f]=function(c){c=c||{};c.userId=c.userId||"@viewer";c.groupId=c.groupId||"@self";return new xf(a,b,c)},"undefined"!==typeof _.vf&&_.vf.push(function(){_.wf.markTameAsFunction(d[f],a)}))}};
var xf=function(a,b,c){this.method=a;this.transport=b;this.rpc=c};xf.prototype.execute=function(a){var b="undefined"!==typeof _.wf&&_.wf.getUseless&&_.wf.getUseless(),c=b?_.wf.getUseless():this,d=b?_.wf.untame(a):a;a=_.Ea.Uj();a.add(this.method,this);a.execute(function(a){a.error?d.call(c,a.error):d.call(c,a[c.method])})};
(0,_.E)("osapi.newBatch.add",_.Ea.Uj.add);(0,_.E)("osapi.newBatch.execute",_.Ea.Uj.execute);(0,_.E)("osapi._registerMethod",_.Ea.Gk);(0,_.E)("osapi._BoundCall",xf);(0,_.E)("osapi._BoundCall.prototype.execute",xf.prototype.execute);
}catch(e){_._DumpException(e)}
try{
var yf=function(a){a=a.split(".");for(var b=window.osapi||window,c;c=a.shift();)if(null!=b[c])b=b[c];else return null;return b},zf=function(a,b){var c=a.split("."),d=window;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d[e]?d=d[e]:d=d[e]={}:d[e]=b};
var Tf;var Sf;var Rf;var Qf;var Pf;var Of;var Ff;var Nf;var Mf;var Lf;var Kf;var If;var Gf;var Ef;var Df;var Cf;var Bf;Bf=null;Cf={};Df=[];Ef=[];Gf=function(a,b){_.Ea.Gk(a,{name:"googleapis",execute:Ff,root:b});var c=yf(a);zf(a,c);if(0!=a.indexOf("googleapis.")){var d=a.substring(a.indexOf(".")+1),e=d.lastIndexOf(".delete");-1!=e&&e+7==d.length&&(d=d.replace(".delete",".remove"));zf("googleapis."+d,c)}};_.Hf=function(a){for(var b in a)a.hasOwnProperty(b)&&(Cf[b]=a[b])};_.Jf=function(a){If("key",a)};
If=function(a,b){null==b?Kf(a):(_.Af=_.Af||{},_.Af[a]=b)};Kf=function(a){_.Af&&delete _.Af[a]};Lf=function(a){a=a||{};if(window.navigator){for(var b=["appVersion","platform","userAgent"],c=[],d=0;d<b.length;d++)window.navigator[b[d]]&&c.push((0,window.encodeURIComponent)(b[d])+"="+(0,window.encodeURIComponent)(window.navigator[b[d]]));a["X-ClientDetails"]=c.join("&")}return a};
Mf=function(a,b){for(var c=0;c<Df.length;c++)window.setTimeout(function(b){return function(){b(a)}}(Df[c]),1);return function(){var a=arguments;b.apply(null,a);for(var c=0;c<Ef.length;c++)window.setTimeout(function(b){return function(){b.apply(null,a)}}(Ef[c]),1)}};Nf=function(a){a.applicationName=Bf;a.clientVersion="1.0.0-alpha";_.Af&&(a.urlParams=_.Af,_.Af.key&&(a.developerKey=_.Af.key))};
Ff=function(a,b){for(var c=this.root||null,d=0;d<a.length;d++){var e=a[d],f;f=e.method;f=f.substring(0,f.indexOf("."));e.jsonrpc="2.0";e.key=e.id;c=e.root||c;(f=Cf[f]||"v1",!e.apiVersion)&&(e.apiVersion=f)}d={};d=_.xe.Qi(d);d=Lf(d);c={requests:a,headers:d,root:c};Nf(c);d=Mf(a,b);_.xe.Me("makeRequest",c,d)};Of=function(a){Df.push(a)};Pf=function(a){Ef.push(a)};Qf=function(a){for(var b=0;b<Df.length;b++)if(Df[b]==a){Df.splice(b,1);break}};
Rf=function(a){for(var b=0;b<Ef.length;b++)if(Ef[b]==a){Ef.splice(b,1);break}};Sf=function(a,b){for(var c=0,d=a.length;c<d;c++){var e=a[c];e.key=e.id;var f=e.params.headers||{},f=_.xe.Qi(f),f=Lf(f);e.params.headers=f;Nf(e.params)}c=Mf(a,b);_.xe.Me("makeHttpRequests",a,c)};
Tf=function(){var a=_.M.nb(),b={debug:"googleapis.config/debug"},c;for(c in b)a[c]&&(0,_.fb)(b[c],"true"==a[c]);for(var d in(0,_.G)("googleapis.config/methods"))Gf(d);(0,_.G)("googleapis.config/versions")&&(0,_.Hf)((0,_.G)("googleapis.config/versions"));(0,_.G)("googleapis.config/developerKey")&&(0,_.Jf)((0,_.G)("googleapis.config/developerKey"));_.Ea.Gk("googleapis.newHttpRequest",{name:"googleapis",execute:Sf});zf("googleapis.newHttpRequest",yf("googleapis.newHttpRequest"))};Tf();
var Uf=function(){this.B={};this.A=_.Ea.Uj()};Uf.prototype.add=function(a,b,c){this.B[a]=c;this.A.add(a,b);return this};Uf.prototype.execute=function(a){var b=this;this.A.execute(function(c){var d={},e=!1,f;for(f in c)if(c.hasOwnProperty(f)){var g=c[f],k=b.B[f];k?k(g):(d[f]=g,e=!0)}e&&a&&a(d)})};
(0,_.E)("googleapis.ApiClient.register",Gf);(0,_.E)("googleapis.ApiClient.setVersions",_.Hf);(0,_.E)("googleapis.ApiClient.setDeveloperKey",_.Jf);(0,_.E)("googleapis.ApiClient.setUrlParameter",If);(0,_.E)("googleapis.ApiClient.removeUrlParameter",Kf);(0,_.E)("googleapis.ApiClient.addExecuteListener",Of);(0,_.E)("googleapis.ApiClient.addResponseListener",Pf);(0,_.E)("googleapis.ApiClient.removeExecuteListener",Qf);(0,_.E)("googleapis.ApiClient.removeResponseListener",Rf);
(0,_.E)("googleapis.ApiClient.init",Tf);(0,_.E)("googleapis.Batch",Uf);(0,_.E)("googleapis.Batch.prototype.add",Uf.prototype.add);(0,_.E)("googleapis.Batch.prototype.execute",Uf.prototype.execute);(0,_.E)("googleapis.init",function(){Tf()});(0,_.E)("googleapis.newBatch",function(){return new Uf});
(0,_.E)("googleapis.newRequest",function(a,b,c){b=b||{};var d={name:"googleapis",execute:Ff,root:c},e=_.Ea.Uj(),f=this;c={};c.method=a;c.transport=d;c.rpc=b;c.execute=function(c){e.add(a,{method:a,rpc:b,transport:d});e.execute(function(b){b.error?c.call(f,b.error):c.call(f,b[a])})};return c});(0,_.E)("googleapis.register",function(a,b){Gf(a,b)});(0,_.E)("googleapis.setUrlParameter",function(a,b){If(a,b)});(0,_.E)("googleapis.removeUrlParameter",function(a){Kf(a)});
(0,_.E)("googleapis.setDeveloperKey",function(a){(0,_.Jf)(a)});(0,_.E)("googleapis.setApplicationName",function(a){Bf=a});(0,_.E)("googleapis.setVersions",function(a){(0,_.Hf)(a)});(0,_.E)("googleapis.addExecuteListener",function(a){Of(a)});(0,_.E)("googleapis.removeExecuteListener",function(a){Qf(a)});(0,_.E)("googleapis.addResponseListener",function(a){Pf(a)});(0,_.E)("googleapis.removeResponseListener",function(a){Rf(a)});(0,_.E)("googleapis.addTransportInitListener",function(a){_.xe.KB(a)}); (0,_.E)("googleapis.removeTransportInitListener",function(a){_.xe.CG(a)});

}catch(e){_._DumpException(e)}
})(_);
// Google Inc.
